<?php

use Illuminate\Database\Seeder;

class DairaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $daira = array(
            array('daira_id' => '1', 'daira_nom' => 'ADRAR', 'wilaya_id' => '1'),
            array('daira_id' => '2', 'daira_nom' => 'AOUGROUT', 'wilaya_id' => '1'),
            array('daira_id' => '3', 'daira_nom' => 'AOULEF', 'wilaya_id' => '1'),
            array('daira_id' => '4', 'daira_nom' => 'BORDJ BADJI MOKHTAR', 'wilaya_id' => '1'),
            array('daira_id' => '5', 'daira_nom' => 'CHAROUINE', 'wilaya_id' => '1'),
            array('daira_id' => '6', 'daira_nom' => 'FENOUGHIL', 'wilaya_id' => '1'),
            array('daira_id' => '7', 'daira_nom' => 'REGGANE', 'wilaya_id' => '1'),
            array('daira_id' => '8', 'daira_nom' => 'TIMIMOUN', 'wilaya_id' => '1'),
            array('daira_id' => '9', 'daira_nom' => 'TINERKOUK', 'wilaya_id' => '1'),
            array('daira_id' => '10', 'daira_nom' => 'TSABIT', 'wilaya_id' => '1'),
            array('daira_id' => '11', 'daira_nom' => 'ZAOUIAT KOUNTA', 'wilaya_id' => '1'),
            array('daira_id' => '12', 'daira_nom' => 'AIN KIHEL', 'wilaya_id' => '2'),
            array('daira_id' => '13', 'daira_nom' => 'AIN LARBAA', 'wilaya_id' => '2'),
            array('daira_id' => '14', 'daira_nom' => 'AIN TEMOUCHENT', 'wilaya_id' => '2'),
            array('daira_id' => '15', 'daira_nom' => 'BENI SAF', 'wilaya_id' => '2'),
            array('daira_id' => '16', 'daira_nom' => 'EL AMRIA', 'wilaya_id' => '2'),
            array('daira_id' => '17', 'daira_nom' => 'EL MALEH', 'wilaya_id' => '2'),
            array('daira_id' => '18', 'daira_nom' => 'HAMMAM BOU HADJAR', 'wilaya_id' => '2'),
            array('daira_id' => '19', 'daira_nom' => 'OULHASSA GHERABA', 'wilaya_id' => '2'),
            array('daira_id' => '20', 'daira_nom' => 'AIN DEFLA', 'wilaya_id' => '3'),
            array('daira_id' => '21', 'daira_nom' => 'AIN LECHIAKH', 'wilaya_id' => '3'),
            array('daira_id' => '22', 'daira_nom' => 'BATHIA', 'wilaya_id' => '3'),
            array('daira_id' => '23', 'daira_nom' => 'BORDJ EL EMIR KHALED', 'wilaya_id' => '3'),
            array('daira_id' => '24', 'daira_nom' => 'BOUMEDFAA', 'wilaya_id' => '3'),
            array('daira_id' => '25', 'daira_nom' => 'DJELIDA', 'wilaya_id' => '3'),
            array('daira_id' => '26', 'daira_nom' => 'DJENDEL', 'wilaya_id' => '3'),
            array('daira_id' => '27', 'daira_nom' => 'EL ABADIA', 'wilaya_id' => '3'),
            array('daira_id' => '28', 'daira_nom' => 'EL AMRA', 'wilaya_id' => '3'),
            array('daira_id' => '29', 'daira_nom' => 'EL ATTAF', 'wilaya_id' => '3'),
            array('daira_id' => '30', 'daira_nom' => 'HAMMAM RIGHA', 'wilaya_id' => '3'),
            array('daira_id' => '31', 'daira_nom' => 'KHEMIS', 'wilaya_id' => '3'),
            array('daira_id' => '32', 'daira_nom' => 'MILIANA', 'wilaya_id' => '3'),
            array('daira_id' => '33', 'daira_nom' => 'ROUINA', 'wilaya_id' => '3'),
            array('daira_id' => '34', 'daira_nom' => 'BAB EL OUED', 'wilaya_id' => '4'),
            array('daira_id' => '35', 'daira_nom' => 'BARAKI', 'wilaya_id' => '4'),
            array('daira_id' => '36', 'daira_nom' => 'BIR MOURAD RAIS', 'wilaya_id' => '4'),
            array('daira_id' => '37', 'daira_nom' => 'BIRTOUTA', 'wilaya_id' => '4'),
            array('daira_id' => '38', 'daira_nom' => 'BOUZAREAH', 'wilaya_id' => '4'),
            array('daira_id' => '39', 'daira_nom' => 'CHERAGA', 'wilaya_id' => '4'),
            array('daira_id' => '40', 'daira_nom' => 'DAR EL BEIDA', 'wilaya_id' => '4'),
            array('daira_id' => '41', 'daira_nom' => 'DRARIA', 'wilaya_id' => '4'),
            array('daira_id' => '42', 'daira_nom' => 'EL HARRACH', 'wilaya_id' => '4'),
            array('daira_id' => '43', 'daira_nom' => 'HUSSEIN DEY', 'wilaya_id' => '4'),
            array('daira_id' => '44', 'daira_nom' => 'ROUIBA', 'wilaya_id' => '4'),
            array('daira_id' => '45', 'daira_nom' => 'SIDI M\'HAMED', 'wilaya_id' => '4'),
            array('daira_id' => '46', 'daira_nom' => 'ZERALDA', 'wilaya_id' => '4'),
            array('daira_id' => '47', 'daira_nom' => 'AIN EL BERDA', 'wilaya_id' => '5'),
            array('daira_id' => '48', 'daira_nom' => 'ANNABA', 'wilaya_id' => '5'),
            array('daira_id' => '49', 'daira_nom' => 'BERRAHAL', 'wilaya_id' => '5'),
            array('daira_id' => '50', 'daira_nom' => 'CHETAIBI', 'wilaya_id' => '5'),
            array('daira_id' => '51', 'daira_nom' => 'EL BOUNI', 'wilaya_id' => '5'),
            array('daira_id' => '52', 'daira_nom' => 'EL HADJAR', 'wilaya_id' => '5'),
            array('daira_id' => '53', 'daira_nom' => 'AIN TAGHROUT', 'wilaya_id' => '6'),
            array('daira_id' => '54', 'daira_nom' => 'BIR KASDALI', 'wilaya_id' => '6'),
            array('daira_id' => '55', 'daira_nom' => 'BORDJ BOU ARRERIDJ', 'wilaya_id' => '6'),
            array('daira_id' => '56', 'daira_nom' => 'BORDJ GHEDIR', 'wilaya_id' => '6'),
            array('daira_id' => '57', 'daira_nom' => 'BORDJ ZEMMOURA', 'wilaya_id' => '6'),
            array('daira_id' => '58', 'daira_nom' => 'DJAAFRA', 'wilaya_id' => '6'),
            array('daira_id' => '59', 'daira_nom' => 'EL HAMADIA', 'wilaya_id' => '6'),
            array('daira_id' => '60', 'daira_nom' => 'MANSOURAH', 'wilaya_id' => '6'),
            array('daira_id' => '61', 'daira_nom' => 'MEDJANA', 'wilaya_id' => '6'),
            array('daira_id' => '62', 'daira_nom' => 'RAS EL OUED', 'wilaya_id' => '6'),
            array('daira_id' => '63', 'daira_nom' => 'AIN DJASSER', 'wilaya_id' => '7'),
            array('daira_id' => '64', 'daira_nom' => 'AIN TOUTA', 'wilaya_id' => '7'),
            array('daira_id' => '65', 'daira_nom' => 'ARRIS', 'wilaya_id' => '7'),
            array('daira_id' => '66', 'daira_nom' => 'BARIKA', 'wilaya_id' => '7'),
            array('daira_id' => '67', 'daira_nom' => 'BATNA', 'wilaya_id' => '7'),
            array('daira_id' => '68', 'daira_nom' => 'BOUZINA', 'wilaya_id' => '7'),
            array('daira_id' => '69', 'daira_nom' => 'CHEMORA', 'wilaya_id' => '7'),
            array('daira_id' => '70', 'daira_nom' => 'DJEZZAR', 'wilaya_id' => '7'),
            array('daira_id' => '71', 'daira_nom' => 'EL MADHER', 'wilaya_id' => '7'),
            array('daira_id' => '72', 'daira_nom' => 'ICHEMOUL', 'wilaya_id' => '7'),
            array('daira_id' => '73', 'daira_nom' => 'MENAA', 'wilaya_id' => '7'),
            array('daira_id' => '74', 'daira_nom' => 'MEROUANA', 'wilaya_id' => '7'),
            array('daira_id' => '75', 'daira_nom' => 'N\'GAOUS', 'wilaya_id' => '7'),
            array('daira_id' => '76', 'daira_nom' => 'OULED SI SLIMANE', 'wilaya_id' => '7'),
            array('daira_id' => '77', 'daira_nom' => 'RAS EL AIOUN', 'wilaya_id' => '7'),
            array('daira_id' => '78', 'daira_nom' => 'SEGGANA', 'wilaya_id' => '7'),
            array('daira_id' => '79', 'daira_nom' => 'SERIANA', 'wilaya_id' => '7'),
            array('daira_id' => '80', 'daira_nom' => 'TAZOULT', 'wilaya_id' => '7'),
            array('daira_id' => '81', 'daira_nom' => 'THENIET EL ABED', 'wilaya_id' => '7'),
            array('daira_id' => '82', 'daira_nom' => 'TIMGAD', 'wilaya_id' => '7'),
            array('daira_id' => '83', 'daira_nom' => 'TKOUT', 'wilaya_id' => '7'),
            array('daira_id' => '84', 'daira_nom' => 'ABADLA', 'wilaya_id' => '8'),
            array('daira_id' => '85', 'daira_nom' => 'BECHAR', 'wilaya_id' => '8'),
            array('daira_id' => '86', 'daira_nom' => 'BENI ABBES', 'wilaya_id' => '8'),
            array('daira_id' => '87', 'daira_nom' => 'BENI OUNIF', 'wilaya_id' => '8'),
            array('daira_id' => '88', 'daira_nom' => 'EL OUATA', 'wilaya_id' => '8'),
            array('daira_id' => '89', 'daira_nom' => 'IGLI', 'wilaya_id' => '8'),
            array('daira_id' => '90', 'daira_nom' => 'KENADSA', 'wilaya_id' => '8'),
            array('daira_id' => '91', 'daira_nom' => 'KERZAZ', 'wilaya_id' => '8'),
            array('daira_id' => '92', 'daira_nom' => 'LAHMAR', 'wilaya_id' => '8'),
            array('daira_id' => '93', 'daira_nom' => 'OULED KHODEIR', 'wilaya_id' => '8'),
            array('daira_id' => '94', 'daira_nom' => 'TABELBALA', 'wilaya_id' => '8'),
            array('daira_id' => '95', 'daira_nom' => 'TAGHIT', 'wilaya_id' => '8'),
            array('daira_id' => '96', 'daira_nom' => 'ADEKAR', 'wilaya_id' => '9'),
            array('daira_id' => '97', 'daira_nom' => 'AKBOU', 'wilaya_id' => '9'),
            array('daira_id' => '98', 'daira_nom' => 'AMIZOUR', 'wilaya_id' => '9'),
            array('daira_id' => '99', 'daira_nom' => 'AOKAS', 'wilaya_id' => '9'),
            array('daira_id' => '100', 'daira_nom' => 'BARBACHA', 'wilaya_id' => '9'),
            array('daira_id' => '101', 'daira_nom' => 'BEJAIA', 'wilaya_id' => '9'),
            array('daira_id' => '102', 'daira_nom' => 'BENI MAOUCHE', 'wilaya_id' => '9'),
            array('daira_id' => '103', 'daira_nom' => 'CHEMINI', 'wilaya_id' => '9'),
            array('daira_id' => '104', 'daira_nom' => 'DARGUINA', 'wilaya_id' => '9'),
            array('daira_id' => '105', 'daira_nom' => 'EL KSEUR', 'wilaya_id' => '9'),
            array('daira_id' => '106', 'daira_nom' => 'IFRI OUZELLAGUENE', 'wilaya_id' => '9'),
            array('daira_id' => '107', 'daira_nom' => 'IGHIL ALI', 'wilaya_id' => '9'),
            array('daira_id' => '108', 'daira_nom' => 'KHERRATA', 'wilaya_id' => '9'),
            array('daira_id' => '109', 'daira_nom' => 'SEDDOUK', 'wilaya_id' => '9'),
            array('daira_id' => '110', 'daira_nom' => 'SIDI AICH', 'wilaya_id' => '9'),
            array('daira_id' => '111', 'daira_nom' => 'SOUK EL TENINE', 'wilaya_id' => '9'),
            array('daira_id' => '112', 'daira_nom' => 'TAZMALT', 'wilaya_id' => '9'),
            array('daira_id' => '113', 'daira_nom' => 'TICHY', 'wilaya_id' => '9'),
            array('daira_id' => '114', 'daira_nom' => 'TIMEZRIT', 'wilaya_id' => '9'),
            array('daira_id' => '115', 'daira_nom' => 'BISKRA', 'wilaya_id' => '10'),
            array('daira_id' => '116', 'daira_nom' => 'DJEMORAH', 'wilaya_id' => '10'),
            array('daira_id' => '117', 'daira_nom' => 'EL KANTARA', 'wilaya_id' => '10'),
            array('daira_id' => '118', 'daira_nom' => 'EL OUTAYA', 'wilaya_id' => '10'),
            array('daira_id' => '119', 'daira_nom' => 'FOUGHALA', 'wilaya_id' => '10'),
            array('daira_id' => '120', 'daira_nom' => 'MECHOUNECHE', 'wilaya_id' => '10'),
            array('daira_id' => '121', 'daira_nom' => 'OULED DJELLAL', 'wilaya_id' => '10'),
            array('daira_id' => '122', 'daira_nom' => 'OURLAL', 'wilaya_id' => '10'),
            array('daira_id' => '123', 'daira_nom' => 'SIDI KHALED', 'wilaya_id' => '10'),
            array('daira_id' => '124', 'daira_nom' => 'SIDI OKBA', 'wilaya_id' => '10'),
            array('daira_id' => '125', 'daira_nom' => 'TOLGA', 'wilaya_id' => '10'),
            array('daira_id' => '126', 'daira_nom' => 'ZERIBET EL OUED', 'wilaya_id' => '10'),
            array('daira_id' => '127', 'daira_nom' => 'BLIDA', 'wilaya_id' => '11'),
            array('daira_id' => '128', 'daira_nom' => 'BOUFARIK', 'wilaya_id' => '11'),
            array('daira_id' => '129', 'daira_nom' => 'BOUGARA', 'wilaya_id' => '11'),
            array('daira_id' => '130', 'daira_nom' => 'BOUINAN', 'wilaya_id' => '11'),
            array('daira_id' => '131', 'daira_nom' => 'EL AFFROUN', 'wilaya_id' => '11'),
            array('daira_id' => '132', 'daira_nom' => 'LARBAA', 'wilaya_id' => '11'),
            array('daira_id' => '133', 'daira_nom' => 'MEFTAH', 'wilaya_id' => '11'),
            array('daira_id' => '134', 'daira_nom' => 'MOUZAIA', 'wilaya_id' => '11'),
            array('daira_id' => '135', 'daira_nom' => 'OUED EL ALLEUG', 'wilaya_id' => '11'),
            array('daira_id' => '136', 'daira_nom' => 'OULED YAICH', 'wilaya_id' => '11'),
            array('daira_id' => '137', 'daira_nom' => 'AIN BESSEM', 'wilaya_id' => '12'),
            array('daira_id' => '138', 'daira_nom' => 'BECHLOUL', 'wilaya_id' => '12'),
            array('daira_id' => '139', 'daira_nom' => 'BIR GHBALOU', 'wilaya_id' => '12'),
            array('daira_id' => '140', 'daira_nom' => 'BORDJ OKHRISS', 'wilaya_id' => '12'),
            array('daira_id' => '141', 'daira_nom' => 'BOUIRA', 'wilaya_id' => '12'),
            array('daira_id' => '142', 'daira_nom' => 'EL HACHIMIA', 'wilaya_id' => '12'),
            array('daira_id' => '143', 'daira_nom' => 'HAIZER', 'wilaya_id' => '12'),
            array('daira_id' => '144', 'daira_nom' => 'KADIRIA', 'wilaya_id' => '12'),
            array('daira_id' => '145', 'daira_nom' => 'LAKHDARIA', 'wilaya_id' => '12'),
            array('daira_id' => '146', 'daira_nom' => 'M\'CHEDALLAH', 'wilaya_id' => '12'),
            array('daira_id' => '147', 'daira_nom' => 'SOUK EL KHEMIS', 'wilaya_id' => '12'),
            array('daira_id' => '148', 'daira_nom' => 'SOUR EL GHOZLANE', 'wilaya_id' => '12'),
            array('daira_id' => '149', 'daira_nom' => 'BAGHLIA', 'wilaya_id' => '13'),
            array('daira_id' => '150', 'daira_nom' => 'BORDJ MENAIEL', 'wilaya_id' => '13'),
            array('daira_id' => '151', 'daira_nom' => 'BOUDOUAOU', 'wilaya_id' => '13'),
            array('daira_id' => '152', 'daira_nom' => 'BOUMERDES', 'wilaya_id' => '13'),
            array('daira_id' => '153', 'daira_nom' => 'DELLYS', 'wilaya_id' => '13'),
            array('daira_id' => '154', 'daira_nom' => 'ISSER', 'wilaya_id' => '13'),
            array('daira_id' => '155', 'daira_nom' => 'KHEMIS EL KHECHNA', 'wilaya_id' => '13'),
            array('daira_id' => '156', 'daira_nom' => 'NACIRIA', 'wilaya_id' => '13'),
            array('daira_id' => '157', 'daira_nom' => 'THENIA', 'wilaya_id' => '13'),
            array('daira_id' => '158', 'daira_nom' => 'ABOU EL HASSANE', 'wilaya_id' => '14'),
            array('daira_id' => '159', 'daira_nom' => 'AIN MERANE', 'wilaya_id' => '14'),
            array('daira_id' => '160', 'daira_nom' => 'BENI HAOUA', 'wilaya_id' => '14'),
            array('daira_id' => '161', 'daira_nom' => 'BOUKADIR', 'wilaya_id' => '14'),
            array('daira_id' => '162', 'daira_nom' => 'CHLEF', 'wilaya_id' => '14'),
            array('daira_id' => '163', 'daira_nom' => 'EL KARIMIA', 'wilaya_id' => '14'),
            array('daira_id' => '164', 'daira_nom' => 'EL MARSA', 'wilaya_id' => '14'),
            array('daira_id' => '165', 'daira_nom' => 'OUED FODDA', 'wilaya_id' => '14'),
            array('daira_id' => '166', 'daira_nom' => 'OULED BEN ABDELKADER', 'wilaya_id' => '14'),
            array('daira_id' => '167', 'daira_nom' => 'OULED FARES', 'wilaya_id' => '14'),
            array('daira_id' => '168', 'daira_nom' => 'TAOUGRIT', 'wilaya_id' => '14'),
            array('daira_id' => '169', 'daira_nom' => 'TENES', 'wilaya_id' => '14'),
            array('daira_id' => '170', 'daira_nom' => 'ZEBOUDJA', 'wilaya_id' => '14'),
            array('daira_id' => '171', 'daira_nom' => 'AIN ABID', 'wilaya_id' => '15'),
            array('daira_id' => '172', 'daira_nom' => 'CONSTANTINE', 'wilaya_id' => '15'),
            array('daira_id' => '173', 'daira_nom' => 'EL KHROUB', 'wilaya_id' => '15'),
            array('daira_id' => '174', 'daira_nom' => 'HAMMA BOUZIANE', 'wilaya_id' => '15'),
            array('daira_id' => '175', 'daira_nom' => 'IBN ZIAD', 'wilaya_id' => '15'),
            array('daira_id' => '176', 'daira_nom' => 'ZIGHOUD YOUCEF', 'wilaya_id' => '15'),
            array('daira_id' => '177', 'daira_nom' => 'AIN EL IBEL', 'wilaya_id' => '16'),
            array('daira_id' => '178', 'daira_nom' => 'AIN OUSSERA', 'wilaya_id' => '16'),
            array('daira_id' => '179', 'daira_nom' => 'BIRINE', 'wilaya_id' => '16'),
            array('daira_id' => '180', 'daira_nom' => 'CHAREF', 'wilaya_id' => '16'),
            array('daira_id' => '181', 'daira_nom' => 'DAR CHIOUKH', 'wilaya_id' => '16'),
            array('daira_id' => '182', 'daira_nom' => 'DJELFA', 'wilaya_id' => '16'),
            array('daira_id' => '183', 'daira_nom' => 'EL IDRISSIA', 'wilaya_id' => '16'),
            array('daira_id' => '184', 'daira_nom' => 'FAIDH EL BOTMA', 'wilaya_id' => '16'),
            array('daira_id' => '185', 'daira_nom' => 'HAD SAHARY', 'wilaya_id' => '16'),
            array('daira_id' => '186', 'daira_nom' => 'HASSI BAHBAH', 'wilaya_id' => '16'),
            array('daira_id' => '187', 'daira_nom' => 'MESSAAD', 'wilaya_id' => '16'),
            array('daira_id' => '188', 'daira_nom' => 'SIDI LAADJEL', 'wilaya_id' => '16'),
            array('daira_id' => '189', 'daira_nom' => 'BOUALEM', 'wilaya_id' => '17'),
            array('daira_id' => '190', 'daira_nom' => 'BOUGTOB', 'wilaya_id' => '17'),
            array('daira_id' => '191', 'daira_nom' => 'BOUSSEMGHOUN', 'wilaya_id' => '17'),
            array('daira_id' => '192', 'daira_nom' => 'EL BAYADH', 'wilaya_id' => '17'),
            array('daira_id' => '193', 'daira_nom' => 'ROGASSA', 'wilaya_id' => '17'),
            array('daira_id' => '194', 'daira_nom' => 'BEN M\'HIDI', 'wilaya_id' => '18'),
            array('daira_id' => '195', 'daira_nom' => 'BESBES', 'wilaya_id' => '18'),
            array('daira_id' => '196', 'daira_nom' => 'BOUHADJAR', 'wilaya_id' => '18'),
            array('daira_id' => '197', 'daira_nom' => 'BOUTELDJA', 'wilaya_id' => '18'),
            array('daira_id' => '198', 'daira_nom' => 'DREAN', 'wilaya_id' => '18'),
            array('daira_id' => '199', 'daira_nom' => 'EL KALA', 'wilaya_id' => '18'),
            array('daira_id' => '200', 'daira_nom' => 'EL TARF', 'wilaya_id' => '18'),
            array('daira_id' => '201', 'daira_nom' => 'BAYADHA', 'wilaya_id' => '19'),
            array('daira_id' => '202', 'daira_nom' => 'DEBILA', 'wilaya_id' => '19'),
            array('daira_id' => '203', 'daira_nom' => 'DJAMAA', 'wilaya_id' => '19'),
            array('daira_id' => '204', 'daira_nom' => 'EL MEGHAIER', 'wilaya_id' => '19'),
            array('daira_id' => '205', 'daira_nom' => 'EL OUED', 'wilaya_id' => '19'),
            array('daira_id' => '206', 'daira_nom' => 'GUEMAR', 'wilaya_id' => '19'),
            array('daira_id' => '207', 'daira_nom' => 'HASSI KHALIFA', 'wilaya_id' => '19'),
            array('daira_id' => '208', 'daira_nom' => 'MAGRANE', 'wilaya_id' => '19'),
            array('daira_id' => '209', 'daira_nom' => 'MIH OUENSA', 'wilaya_id' => '19'),
            array('daira_id' => '210', 'daira_nom' => 'REGUIBA', 'wilaya_id' => '19'),
            array('daira_id' => '211', 'daira_nom' => 'ROBBAH', 'wilaya_id' => '19'),
            array('daira_id' => '212', 'daira_nom' => 'TALEB LARBI', 'wilaya_id' => '19'),
            array('daira_id' => '213', 'daira_nom' => 'BERRIANE', 'wilaya_id' => '20'),
            array('daira_id' => '214', 'daira_nom' => 'BOUNOURA', 'wilaya_id' => '20'),
            array('daira_id' => '215', 'daira_nom' => 'DHAYET BEN DHAHOUA', 'wilaya_id' => '20'),
            array('daira_id' => '216', 'daira_nom' => 'EL GUERRARA', 'wilaya_id' => '20'),
            array('daira_id' => '217', 'daira_nom' => 'EL MENIA', 'wilaya_id' => '20'),
            array('daira_id' => '218', 'daira_nom' => 'GHARDAIA', 'wilaya_id' => '20'),
            array('daira_id' => '219', 'daira_nom' => 'MANSOURAH', 'wilaya_id' => '20'),
            array('daira_id' => '220', 'daira_nom' => 'METLILI', 'wilaya_id' => '20'),
            array('daira_id' => '221', 'daira_nom' => 'ZELFANA', 'wilaya_id' => '20'),
            array('daira_id' => '222', 'daira_nom' => 'AIN HESSAINIA', 'wilaya_id' => '21'),
            array('daira_id' => '223', 'daira_nom' => 'AIN MAKHLOUF', 'wilaya_id' => '21'),
            array('daira_id' => '224', 'daira_nom' => 'BOUCHEGOUF', 'wilaya_id' => '21'),
            array('daira_id' => '225', 'daira_nom' => 'GUELAAT BOUSBAA', 'wilaya_id' => '21'),
            array('daira_id' => '226', 'daira_nom' => 'GUELMA', 'wilaya_id' => '21'),
            array('daira_id' => '227', 'daira_nom' => 'HAMMAM DEBAGH', 'wilaya_id' => '21'),
            array('daira_id' => '228', 'daira_nom' => 'HAMMAM N\'BAILS', 'wilaya_id' => '21'),
            array('daira_id' => '229', 'daira_nom' => 'HELIOPOLIS', 'wilaya_id' => '21'),
            array('daira_id' => '230', 'daira_nom' => 'KHEZARAS', 'wilaya_id' => '21'),
            array('daira_id' => '231', 'daira_nom' => 'OUED ZENATI', 'wilaya_id' => '21'),
            array('daira_id' => '232', 'daira_nom' => 'DJANET', 'wilaya_id' => '22'),
            array('daira_id' => '233', 'daira_nom' => 'ILLIZI', 'wilaya_id' => '22'),
            array('daira_id' => '234', 'daira_nom' => 'IN AMENAS', 'wilaya_id' => '22'),
            array('daira_id' => '235', 'daira_nom' => 'CHEKFA', 'wilaya_id' => '23'),
            array('daira_id' => '236', 'daira_nom' => 'DJIMLA', 'wilaya_id' => '23'),
            array('daira_id' => '237', 'daira_nom' => 'EL ANCER', 'wilaya_id' => '23'),
            array('daira_id' => '238', 'daira_nom' => 'EL AOUANA', 'wilaya_id' => '23'),
            array('daira_id' => '239', 'daira_nom' => 'EL MILIA', 'wilaya_id' => '23'),
            array('daira_id' => '240', 'daira_nom' => 'JIJEL', 'wilaya_id' => '23'),
            array('daira_id' => '241', 'daira_nom' => 'SETTARA', 'wilaya_id' => '23'),
            array('daira_id' => '242', 'daira_nom' => 'SIDI MAROUF', 'wilaya_id' => '23'),
            array('daira_id' => '243', 'daira_nom' => 'TAHER', 'wilaya_id' => '23'),
            array('daira_id' => '244', 'daira_nom' => 'TEXENNA', 'wilaya_id' => '23'),
            array('daira_id' => '245', 'daira_nom' => 'ZIAMAH MANSOURIAH', 'wilaya_id' => '23'),
            array('daira_id' => '246', 'daira_nom' => 'AIN TOUILA', 'wilaya_id' => '24'),
            array('daira_id' => '247', 'daira_nom' => 'BABAR', 'wilaya_id' => '24'),
            array('daira_id' => '248', 'daira_nom' => 'BOUHMAMA', 'wilaya_id' => '24'),
            array('daira_id' => '249', 'daira_nom' => 'CHECHAR', 'wilaya_id' => '24'),
            array('daira_id' => '250', 'daira_nom' => 'EL HAMMA', 'wilaya_id' => '24'),
            array('daira_id' => '251', 'daira_nom' => 'KAIS', 'wilaya_id' => '24'),
            array('daira_id' => '252', 'daira_nom' => 'KHENCHELA', 'wilaya_id' => '24'),
            array('daira_id' => '253', 'daira_nom' => 'OULED RECHACHE', 'wilaya_id' => '24'),
            array('daira_id' => '254', 'daira_nom' => 'AFLOU', 'wilaya_id' => '25'),
            array('daira_id' => '255', 'daira_nom' => 'AIN MADHI', 'wilaya_id' => '25'),
            array('daira_id' => '256', 'daira_nom' => 'BRIDA', 'wilaya_id' => '25'),
            array('daira_id' => '257', 'daira_nom' => 'EL GHICHA', 'wilaya_id' => '25'),
            array('daira_id' => '258', 'daira_nom' => 'GUELTAT SIDI SAAD', 'wilaya_id' => '25'),
            array('daira_id' => '259', 'daira_nom' => 'HASSI R\'MEL', 'wilaya_id' => '25'),
            array('daira_id' => '260', 'daira_nom' => 'KSAR EL HIRANE', 'wilaya_id' => '25'),
            array('daira_id' => '261', 'daira_nom' => 'LAGHOUAT', 'wilaya_id' => '25'),
            array('daira_id' => '262', 'daira_nom' => 'OUED MORRA', 'wilaya_id' => '25'),
            array('daira_id' => '263', 'daira_nom' => 'SIDI MAKHLOUF', 'wilaya_id' => '25'),
            array('daira_id' => '264', 'daira_nom' => 'AIN FARES', 'wilaya_id' => '26'),
            array('daira_id' => '265', 'daira_nom' => 'AIN FEKAN', 'wilaya_id' => '26'),
            array('daira_id' => '266', 'daira_nom' => 'AOUF', 'wilaya_id' => '26'),
            array('daira_id' => '267', 'daira_nom' => 'BOUHANIFIA', 'wilaya_id' => '26'),
            array('daira_id' => '268', 'daira_nom' => 'EL BORDJ', 'wilaya_id' => '26'),
            array('daira_id' => '269', 'daira_nom' => 'GHRISS', 'wilaya_id' => '26'),
            array('daira_id' => '270', 'daira_nom' => 'HACHEM', 'wilaya_id' => '26'),
            array('daira_id' => '271', 'daira_nom' => 'MASCARA', 'wilaya_id' => '26'),
            array('daira_id' => '272', 'daira_nom' => 'MOHAMMADIA', 'wilaya_id' => '26'),
            array('daira_id' => '273', 'daira_nom' => 'OGGAZ', 'wilaya_id' => '26'),
            array('daira_id' => '274', 'daira_nom' => 'OUED EL ABTAL', 'wilaya_id' => '26'),
            array('daira_id' => '275', 'daira_nom' => 'OUED TARIA', 'wilaya_id' => '26'),
            array('daira_id' => '276', 'daira_nom' => 'SIG', 'wilaya_id' => '26'),
            array('daira_id' => '277', 'daira_nom' => 'TIGHENNIF', 'wilaya_id' => '26'),
            array('daira_id' => '278', 'daira_nom' => 'TIZI', 'wilaya_id' => '26'),
            array('daira_id' => '279', 'daira_nom' => 'ZAHANA', 'wilaya_id' => '26'),
            array('daira_id' => '280', 'daira_nom' => 'AIN BOUCIF', 'wilaya_id' => '27'),
            array('daira_id' => '281', 'daira_nom' => 'AZIZ', 'wilaya_id' => '27'),
            array('daira_id' => '282', 'daira_nom' => 'BENI SLIMANE', 'wilaya_id' => '27'),
            array('daira_id' => '283', 'daira_nom' => 'BERROUAGHIA', 'wilaya_id' => '27'),
            array('daira_id' => '284', 'daira_nom' => 'CHAHBOUNIA', 'wilaya_id' => '27'),
            array('daira_id' => '285', 'daira_nom' => 'CHELLALAT EL ADHAOURA', 'wilaya_id' => '27'),
            array('daira_id' => '286', 'daira_nom' => 'EL AZIZIA', 'wilaya_id' => '27'),
            array('daira_id' => '287', 'daira_nom' => 'EL OMARIA', 'wilaya_id' => '27'),
            array('daira_id' => '288', 'daira_nom' => 'GUELB EL KEBIR', 'wilaya_id' => '27'),
            array('daira_id' => '289', 'daira_nom' => 'KSAR EL BOUKHARI', 'wilaya_id' => '27'),
            array('daira_id' => '290', 'daira_nom' => 'MEDEA', 'wilaya_id' => '27'),
            array('daira_id' => '291', 'daira_nom' => 'OUAMRI', 'wilaya_id' => '27'),
            array('daira_id' => '292', 'daira_nom' => 'OULED ANTAR', 'wilaya_id' => '27'),
            array('daira_id' => '293', 'daira_nom' => 'OUZERA', 'wilaya_id' => '27'),
            array('daira_id' => '294', 'daira_nom' => 'SEGHOUANE', 'wilaya_id' => '27'),
            array('daira_id' => '295', 'daira_nom' => 'SI MAHDJOUB', 'wilaya_id' => '27'),
            array('daira_id' => '296', 'daira_nom' => 'SIDI NAAMANE', 'wilaya_id' => '27'),
            array('daira_id' => '297', 'daira_nom' => 'SOUAGHI', 'wilaya_id' => '27'),
            array('daira_id' => '298', 'daira_nom' => 'TABLAT', 'wilaya_id' => '27'),
            array('daira_id' => '299', 'daira_nom' => 'AIN BEIDA HARRICHE', 'wilaya_id' => '28'),
            array('daira_id' => '300', 'daira_nom' => 'BOUHATEM', 'wilaya_id' => '28'),
            array('daira_id' => '301', 'daira_nom' => 'CHELGHOUM LAID', 'wilaya_id' => '28'),
            array('daira_id' => '302', 'daira_nom' => 'FERDJIOUA', 'wilaya_id' => '28'),
            array('daira_id' => '303', 'daira_nom' => 'GRAREM GOUGA', 'wilaya_id' => '28'),
            array('daira_id' => '304', 'daira_nom' => 'MILA', 'wilaya_id' => '28'),
            array('daira_id' => '305', 'daira_nom' => 'OUED ENDJA', 'wilaya_id' => '28'),
            array('daira_id' => '306', 'daira_nom' => 'ROUACHED', 'wilaya_id' => '28'),
            array('daira_id' => '307', 'daira_nom' => 'SIDI MEROUANE', 'wilaya_id' => '28'),
            array('daira_id' => '308', 'daira_nom' => 'TADJENANET', 'wilaya_id' => '28'),
            array('daira_id' => '309', 'daira_nom' => 'TASSADANE HADDADA', 'wilaya_id' => '28'),
            array('daira_id' => '310', 'daira_nom' => 'TELEGHMA', 'wilaya_id' => '28'),
            array('daira_id' => '311', 'daira_nom' => 'TERRAI BAINEN', 'wilaya_id' => '28'),
            array('daira_id' => '312', 'daira_nom' => 'ACHAACHA', 'wilaya_id' => '29'),
            array('daira_id' => '313', 'daira_nom' => 'AIN NOUICY', 'wilaya_id' => '29'),
            array('daira_id' => '314', 'daira_nom' => 'AIN TEDELES', 'wilaya_id' => '29'),
            array('daira_id' => '315', 'daira_nom' => 'BOUGUIRAT', 'wilaya_id' => '29'),
            array('daira_id' => '316', 'daira_nom' => 'HASSI MAMECHE', 'wilaya_id' => '29'),
            array('daira_id' => '317', 'daira_nom' => 'KHEIR EDDINE', 'wilaya_id' => '29'),
            array('daira_id' => '318', 'daira_nom' => 'MESRA', 'wilaya_id' => '29'),
            array('daira_id' => '319', 'daira_nom' => 'MOSTAGANEM', 'wilaya_id' => '29'),
            array('daira_id' => '320', 'daira_nom' => 'SIDI ALI', 'wilaya_id' => '29'),
            array('daira_id' => '321', 'daira_nom' => 'SIDI LAKHDAR', 'wilaya_id' => '29'),
            array('daira_id' => '322', 'daira_nom' => 'AIN EL HADJEL', 'wilaya_id' => '30'),
            array('daira_id' => '323', 'daira_nom' => 'AIN EL MELH', 'wilaya_id' => '30'),
            array('daira_id' => '324', 'daira_nom' => 'BEN SROUR', 'wilaya_id' => '30'),
            array('daira_id' => '325', 'daira_nom' => 'BOUSAADA', 'wilaya_id' => '30'),
            array('daira_id' => '326', 'daira_nom' => 'CHELLAL', 'wilaya_id' => '30'),
            array('daira_id' => '327', 'daira_nom' => 'DJEBEL MESSAAD', 'wilaya_id' => '30'),
            array('daira_id' => '328', 'daira_nom' => 'HAMMAM DALAA', 'wilaya_id' => '30'),
            array('daira_id' => '329', 'daira_nom' => 'KHOUBANA', 'wilaya_id' => '30'),
            array('daira_id' => '330', 'daira_nom' => 'MAGRA', 'wilaya_id' => '30'),
            array('daira_id' => '331', 'daira_nom' => 'MEDJEDEL', 'wilaya_id' => '30'),
            array('daira_id' => '332', 'daira_nom' => 'M\'SILA', 'wilaya_id' => '30'),
            array('daira_id' => '333', 'daira_nom' => 'OULED DERRADJ', 'wilaya_id' => '30'),
            array('daira_id' => '334', 'daira_nom' => 'OULED SIDI BRAHIM', 'wilaya_id' => '30'),
            array('daira_id' => '335', 'daira_nom' => 'SIDI AISSA', 'wilaya_id' => '30'),
            array('daira_id' => '336', 'daira_nom' => 'SIDI AMEUR', 'wilaya_id' => '30'),
            array('daira_id' => '337', 'daira_nom' => 'AIN SEFRA', 'wilaya_id' => '31'),
            array('daira_id' => '338', 'daira_nom' => 'ASLA', 'wilaya_id' => '31'),
            array('daira_id' => '339', 'daira_nom' => 'MECHERIA', 'wilaya_id' => '31'),
            array('daira_id' => '340', 'daira_nom' => 'MEKMEN BEN AMAR', 'wilaya_id' => '31'),
            array('daira_id' => '341', 'daira_nom' => 'MOGHRAR', 'wilaya_id' => '31'),
            array('daira_id' => '342', 'daira_nom' => 'NAAMA', 'wilaya_id' => '31'),
            array('daira_id' => '343', 'daira_nom' => 'SFISSIFA', 'wilaya_id' => '31'),
            array('daira_id' => '344', 'daira_nom' => 'AIN TURK', 'wilaya_id' => '32'),
            array('daira_id' => '345', 'daira_nom' => 'ARZEW', 'wilaya_id' => '32'),
            array('daira_id' => '346', 'daira_nom' => 'BETHIOUA', 'wilaya_id' => '32'),
            array('daira_id' => '347', 'daira_nom' => 'BIR EL DJIR', 'wilaya_id' => '32'),
            array('daira_id' => '348', 'daira_nom' => 'BOUTLELIS', 'wilaya_id' => '32'),
            array('daira_id' => '349', 'daira_nom' => 'ES SENIA', 'wilaya_id' => '32'),
            array('daira_id' => '350', 'daira_nom' => 'GDYEL', 'wilaya_id' => '32'),
            array('daira_id' => '351', 'daira_nom' => 'ORAN', 'wilaya_id' => '32'),
            array('daira_id' => '352', 'daira_nom' => 'OUED TLELAT', 'wilaya_id' => '32'),
            array('daira_id' => '353', 'daira_nom' => 'EL BORMA', 'wilaya_id' => '33'),
            array('daira_id' => '354', 'daira_nom' => 'EL-HADJIRA', 'wilaya_id' => '33'),
            array('daira_id' => '355', 'daira_nom' => 'HASSI MESSAOUD', 'wilaya_id' => '33'),
            array('daira_id' => '356', 'daira_nom' => 'MEGARINE', 'wilaya_id' => '33'),
            array('daira_id' => '357', 'daira_nom' => 'N\'GOUSSA', 'wilaya_id' => '33'),
            array('daira_id' => '358', 'daira_nom' => 'OUARGLA', 'wilaya_id' => '33'),
            array('daira_id' => '359', 'daira_nom' => 'SIDI KHOUILED', 'wilaya_id' => '33'),
            array('daira_id' => '360', 'daira_nom' => 'TAIBET', 'wilaya_id' => '33'),
            array('daira_id' => '361', 'daira_nom' => 'TEMACINE', 'wilaya_id' => '33'),
            array('daira_id' => '362', 'daira_nom' => 'TOUGGOURT', 'wilaya_id' => '33'),
            array('daira_id' => '363', 'daira_nom' => 'AIN BABOUCHE', 'wilaya_id' => '34'),
            array('daira_id' => '364', 'daira_nom' => 'AIN BEIDA', 'wilaya_id' => '34'),
            array('daira_id' => '365', 'daira_nom' => 'AIN FEKROUN', 'wilaya_id' => '34'),
            array('daira_id' => '366', 'daira_nom' => 'AIN KERCHA', 'wilaya_id' => '34'),
            array('daira_id' => '367', 'daira_nom' => 'AIN M\'LILA', 'wilaya_id' => '34'),
            array('daira_id' => '368', 'daira_nom' => 'DHALAA', 'wilaya_id' => '34'),
            array('daira_id' => '369', 'daira_nom' => 'F\'KIRINA', 'wilaya_id' => '34'),
            array('daira_id' => '370', 'daira_nom' => 'KSAR SBAHI', 'wilaya_id' => '34'),
            array('daira_id' => '371', 'daira_nom' => 'MESKIANA', 'wilaya_id' => '34'),
            array('daira_id' => '372', 'daira_nom' => 'OUM EL BOUAGHI', 'wilaya_id' => '34'),
            array('daira_id' => '373', 'daira_nom' => 'SIGUS', 'wilaya_id' => '34'),
            array('daira_id' => '374', 'daira_nom' => 'SOUK NAAMANE', 'wilaya_id' => '34'),
            array('daira_id' => '375', 'daira_nom' => 'AIN TAREK', 'wilaya_id' => '35'),
            array('daira_id' => '376', 'daira_nom' => 'AMMI MOUSSA', 'wilaya_id' => '35'),
            array('daira_id' => '377', 'daira_nom' => 'DJIDIOUIA', 'wilaya_id' => '35'),
            array('daira_id' => '378', 'daira_nom' => 'EL H\'MADNA', 'wilaya_id' => '35'),
            array('daira_id' => '379', 'daira_nom' => 'EL MATMAR', 'wilaya_id' => '35'),
            array('daira_id' => '380', 'daira_nom' => 'MAZOUNA', 'wilaya_id' => '35'),
            array('daira_id' => '381', 'daira_nom' => 'MENDES', 'wilaya_id' => '35'),
            array('daira_id' => '382', 'daira_nom' => 'OUED RHIOU', 'wilaya_id' => '35'),
            array('daira_id' => '383', 'daira_nom' => 'RAMKA', 'wilaya_id' => '35'),
            array('daira_id' => '384', 'daira_nom' => 'RELIZANE', 'wilaya_id' => '35'),
            array('daira_id' => '385', 'daira_nom' => 'SIDI M\'HAMED BEN ALI', 'wilaya_id' => '35'),
            array('daira_id' => '386', 'daira_nom' => 'YELLEL', 'wilaya_id' => '35'),
            array('daira_id' => '387', 'daira_nom' => 'ZEMMOURA', 'wilaya_id' => '35'),
            array('daira_id' => '388', 'daira_nom' => 'AIN EL HADJAR', 'wilaya_id' => '36'),
            array('daira_id' => '389', 'daira_nom' => 'EL HASSASNA', 'wilaya_id' => '36'),
            array('daira_id' => '390', 'daira_nom' => 'OULED BRAHIM', 'wilaya_id' => '36'),
            array('daira_id' => '391', 'daira_nom' => 'SAIDA', 'wilaya_id' => '36'),
            array('daira_id' => '392', 'daira_nom' => 'SIDI BOUBEKEUR', 'wilaya_id' => '36'),
            array('daira_id' => '393', 'daira_nom' => 'YOUB', 'wilaya_id' => '36'),
            array('daira_id' => '394', 'daira_nom' => 'AIN ARNAT', 'wilaya_id' => '37'),
            array('daira_id' => '395', 'daira_nom' => 'AIN AZEL', 'wilaya_id' => '37'),
            array('daira_id' => '396', 'daira_nom' => 'AIN EL KEBIRA', 'wilaya_id' => '37'),
            array('daira_id' => '397', 'daira_nom' => 'AIN OULMENE', 'wilaya_id' => '37'),
            array('daira_id' => '398', 'daira_nom' => 'AMOUCHA', 'wilaya_id' => '37'),
            array('daira_id' => '399', 'daira_nom' => 'BABOR', 'wilaya_id' => '37'),
            array('daira_id' => '400', 'daira_nom' => 'BENI AZIZ', 'wilaya_id' => '37'),
            array('daira_id' => '401', 'daira_nom' => 'BENI OURTILANE', 'wilaya_id' => '37'),
            array('daira_id' => '402', 'daira_nom' => 'BIR EL ARCH', 'wilaya_id' => '37'),
            array('daira_id' => '403', 'daira_nom' => 'BOUANDAS', 'wilaya_id' => '37'),
            array('daira_id' => '404', 'daira_nom' => 'BOUGAA', 'wilaya_id' => '37'),
            array('daira_id' => '405', 'daira_nom' => 'DJEMILA', 'wilaya_id' => '37'),
            array('daira_id' => '406', 'daira_nom' => 'EL EULMA', 'wilaya_id' => '37'),
            array('daira_id' => '407', 'daira_nom' => 'GUENZET', 'wilaya_id' => '37'),
            array('daira_id' => '408', 'daira_nom' => 'GUIDJEL', 'wilaya_id' => '37'),
            array('daira_id' => '409', 'daira_nom' => 'HAMMAM GUERGOUR', 'wilaya_id' => '37'),
            array('daira_id' => '410', 'daira_nom' => 'HAMMAM SOKHNA', 'wilaya_id' => '37'),
            array('daira_id' => '411', 'daira_nom' => 'MAOKLANE', 'wilaya_id' => '37'),
            array('daira_id' => '412', 'daira_nom' => 'SALAH BEY', 'wilaya_id' => '37'),
            array('daira_id' => '413', 'daira_nom' => 'SETIF', 'wilaya_id' => '37'),
            array('daira_id' => '414', 'daira_nom' => 'AIN EL BERD', 'wilaya_id' => '38'),
            array('daira_id' => '415', 'daira_nom' => 'BEN BADIS', 'wilaya_id' => '38'),
            array('daira_id' => '416', 'daira_nom' => 'MARHOUM', 'wilaya_id' => '38'),
            array('daira_id' => '417', 'daira_nom' => 'MERINE', 'wilaya_id' => '38'),
            array('daira_id' => '418', 'daira_nom' => 'MOSTEFA BEN BRAHIM', 'wilaya_id' => '38'),
            array('daira_id' => '419', 'daira_nom' => 'MOULAY SLISSEN', 'wilaya_id' => '38'),
            array('daira_id' => '420', 'daira_nom' => 'RAS EL MA', 'wilaya_id' => '38'),
            array('daira_id' => '421', 'daira_nom' => 'SFISEF', 'wilaya_id' => '38'),
            array('daira_id' => '422', 'daira_nom' => 'SIDI ALI BEN YOUB', 'wilaya_id' => '38'),
            array('daira_id' => '423', 'daira_nom' => 'SIDI ALI BOUSSIDI', 'wilaya_id' => '38'),
            array('daira_id' => '424', 'daira_nom' => 'SIDI BEL ABBES', 'wilaya_id' => '38'),
            array('daira_id' => '425', 'daira_nom' => 'SIDI LAHCENE', 'wilaya_id' => '38'),
            array('daira_id' => '426', 'daira_nom' => 'TELAGH', 'wilaya_id' => '38'),
            array('daira_id' => '427', 'daira_nom' => 'TENIRA', 'wilaya_id' => '38'),
            array('daira_id' => '428', 'daira_nom' => 'TESSALA', 'wilaya_id' => '38'),
            array('daira_id' => '429', 'daira_nom' => 'AIN KECHRA', 'wilaya_id' => '39'),
            array('daira_id' => '430', 'daira_nom' => 'AZZABA', 'wilaya_id' => '39'),
            array('daira_id' => '431', 'daira_nom' => 'BEN AZZOUZ', 'wilaya_id' => '39'),
            array('daira_id' => '432', 'daira_nom' => 'COLLO', 'wilaya_id' => '39'),
            array('daira_id' => '433', 'daira_nom' => 'EL HADAIEK', 'wilaya_id' => '39'),
            array('daira_id' => '434', 'daira_nom' => 'EL HARROUCH', 'wilaya_id' => '39'),
            array('daira_id' => '435', 'daira_nom' => 'OULED ATTIA', 'wilaya_id' => '39'),
            array('daira_id' => '436', 'daira_nom' => 'OUM TOUB', 'wilaya_id' => '39'),
            array('daira_id' => '437', 'daira_nom' => 'RAMDANE DJAMEL', 'wilaya_id' => '39'),
            array('daira_id' => '438', 'daira_nom' => 'SIDI MEZGHICHE', 'wilaya_id' => '39'),
            array('daira_id' => '439', 'daira_nom' => 'SKIKDA', 'wilaya_id' => '39'),
            array('daira_id' => '440', 'daira_nom' => 'TAMALOUS', 'wilaya_id' => '39'),
            array('daira_id' => '441', 'daira_nom' => 'ZITOUNA', 'wilaya_id' => '39'),
            array('daira_id' => '442', 'daira_nom' => 'BIR BOUHOUCHE', 'wilaya_id' => '40'),
            array('daira_id' => '443', 'daira_nom' => 'HADDADA', 'wilaya_id' => '40'),
            array('daira_id' => '444', 'daira_nom' => 'M\'DAOUROUCHE', 'wilaya_id' => '40'),
            array('daira_id' => '445', 'daira_nom' => 'MECHROHA', 'wilaya_id' => '40'),
            array('daira_id' => '446', 'daira_nom' => 'MERAHNA', 'wilaya_id' => '40'),
            array('daira_id' => '447', 'daira_nom' => 'OULED DRISS', 'wilaya_id' => '40'),
            array('daira_id' => '448', 'daira_nom' => 'OUM EL ADHAIM', 'wilaya_id' => '40'),
            array('daira_id' => '449', 'daira_nom' => 'SEDRATA', 'wilaya_id' => '40'),
            array('daira_id' => '450', 'daira_nom' => 'SOUK AHRAS', 'wilaya_id' => '40'),
            array('daira_id' => '451', 'daira_nom' => 'TAOURA', 'wilaya_id' => '40'),
            array('daira_id' => '452', 'daira_nom' => 'IN GHAR', 'wilaya_id' => '41'),
            array('daira_id' => '453', 'daira_nom' => 'IN GUEZZAM', 'wilaya_id' => '41'),
            array('daira_id' => '454', 'daira_nom' => 'IN SALAH', 'wilaya_id' => '41'),
            array('daira_id' => '455', 'daira_nom' => 'SILET', 'wilaya_id' => '41'),
            array('daira_id' => '456', 'daira_nom' => 'TAMANRASSET', 'wilaya_id' => '41'),
            array('daira_id' => '457', 'daira_nom' => 'TAZROUK', 'wilaya_id' => '41'),
            array('daira_id' => '458', 'daira_nom' => 'TIN ZOUATINE', 'wilaya_id' => '41'),
            array('daira_id' => '459', 'daira_nom' => 'BIR EL ATER', 'wilaya_id' => '42'),
            array('daira_id' => '460', 'daira_nom' => 'BIR MOKADEM', 'wilaya_id' => '42'),
            array('daira_id' => '461', 'daira_nom' => 'CHERIA', 'wilaya_id' => '42'),
            array('daira_id' => '462', 'daira_nom' => 'EL AOUINET', 'wilaya_id' => '42'),
            array('daira_id' => '463', 'daira_nom' => 'EL KOUIF', 'wilaya_id' => '42'),
            array('daira_id' => '464', 'daira_nom' => 'EL MALABIOD', 'wilaya_id' => '42'),
            array('daira_id' => '465', 'daira_nom' => 'EL OGLA', 'wilaya_id' => '42'),
            array('daira_id' => '466', 'daira_nom' => 'MORSOTT', 'wilaya_id' => '42'),
            array('daira_id' => '467', 'daira_nom' => 'NEGRINE', 'wilaya_id' => '42'),
            array('daira_id' => '468', 'daira_nom' => 'OUENZA', 'wilaya_id' => '42'),
            array('daira_id' => '469', 'daira_nom' => 'OUM ALI', 'wilaya_id' => '42'),
            array('daira_id' => '470', 'daira_nom' => 'TEBESSA', 'wilaya_id' => '42'),
            array('daira_id' => '471', 'daira_nom' => 'AIN DEHEB', 'wilaya_id' => '43'),
            array('daira_id' => '472', 'daira_nom' => 'AIN KERMES', 'wilaya_id' => '43'),
            array('daira_id' => '473', 'daira_nom' => 'DAHMOUNI', 'wilaya_id' => '43'),
            array('daira_id' => '474', 'daira_nom' => 'FRENDA', 'wilaya_id' => '43'),
            array('daira_id' => '475', 'daira_nom' => 'HAMADIA', 'wilaya_id' => '43'),
            array('daira_id' => '476', 'daira_nom' => 'KSAR CHELLALA', 'wilaya_id' => '43'),
            array('daira_id' => '477', 'daira_nom' => 'MAHDIA', 'wilaya_id' => '43'),
            array('daira_id' => '478', 'daira_nom' => 'MECHRAA SFA', 'wilaya_id' => '43'),
            array('daira_id' => '479', 'daira_nom' => 'MEDROUSSA', 'wilaya_id' => '43'),
            array('daira_id' => '480', 'daira_nom' => 'MEGHILA', 'wilaya_id' => '43'),
            array('daira_id' => '481', 'daira_nom' => 'OUED LILI', 'wilaya_id' => '43'),
            array('daira_id' => '482', 'daira_nom' => 'RAHOUIA', 'wilaya_id' => '43'),
            array('daira_id' => '483', 'daira_nom' => 'SOUGUEUR', 'wilaya_id' => '43'),
            array('daira_id' => '484', 'daira_nom' => 'TIARET', 'wilaya_id' => '43'),
            array('daira_id' => '485', 'daira_nom' => 'TINDOUF', 'wilaya_id' => '44'),
            array('daira_id' => '486', 'daira_nom' => 'AHMAR EL AIN', 'wilaya_id' => '45'),
            array('daira_id' => '487', 'daira_nom' => 'BOU ISMAIL', 'wilaya_id' => '45'),
            array('daira_id' => '488', 'daira_nom' => 'CHERCHELL', 'wilaya_id' => '45'),
            array('daira_id' => '489', 'daira_nom' => 'DAMOUS', 'wilaya_id' => '45'),
            array('daira_id' => '490', 'daira_nom' => 'FOUKA', 'wilaya_id' => '45'),
            array('daira_id' => '491', 'daira_nom' => 'GOURAYA', 'wilaya_id' => '45'),
            array('daira_id' => '492', 'daira_nom' => 'HADJOUT', 'wilaya_id' => '45'),
            array('daira_id' => '493', 'daira_nom' => 'KOLEA', 'wilaya_id' => '45'),
            array('daira_id' => '494', 'daira_nom' => 'SIDI AMAR', 'wilaya_id' => '45'),
            array('daira_id' => '495', 'daira_nom' => 'TIPAZA', 'wilaya_id' => '45'),
            array('daira_id' => '496', 'daira_nom' => 'AMMARI', 'wilaya_id' => '46'),
            array('daira_id' => '497', 'daira_nom' => 'BORDJ BOUNAAMA', 'wilaya_id' => '46'),
            array('daira_id' => '498', 'daira_nom' => 'BORDJ EMIR ABDELKADER', 'wilaya_id' => '46'),
            array('daira_id' => '499', 'daira_nom' => 'KHEMISTI', 'wilaya_id' => '46'),
            array('daira_id' => '500', 'daira_nom' => 'LARDJEM', 'wilaya_id' => '46'),
            array('daira_id' => '501', 'daira_nom' => 'LAZHARIA', 'wilaya_id' => '46'),
            array('daira_id' => '502', 'daira_nom' => 'THENIET EL HAD', 'wilaya_id' => '46'),
            array('daira_id' => '503', 'daira_nom' => 'TISSEMSILT', 'wilaya_id' => '46'),
            array('daira_id' => '504', 'daira_nom' => 'AIN EL HAMMAM', 'wilaya_id' => '47'),
            array('daira_id' => '505', 'daira_nom' => 'AZAZGA', 'wilaya_id' => '47'),
            array('daira_id' => '506', 'daira_nom' => 'AZEFFOUN', 'wilaya_id' => '47'),
            array('daira_id' => '507', 'daira_nom' => 'BENI DOUALA', 'wilaya_id' => '47'),
            array('daira_id' => '508', 'daira_nom' => 'BENNI YENNI', 'wilaya_id' => '47'),
            array('daira_id' => '509', 'daira_nom' => 'BOGHNI', 'wilaya_id' => '47'),
            array('daira_id' => '510', 'daira_nom' => 'BOUZEGUENE', 'wilaya_id' => '47'),
            array('daira_id' => '511', 'daira_nom' => 'DRAA BEN KHEDDA', 'wilaya_id' => '47'),
            array('daira_id' => '512', 'daira_nom' => 'DRAA EL MIZAN', 'wilaya_id' => '47'),
            array('daira_id' => '513', 'daira_nom' => 'IFERHOUNENE', 'wilaya_id' => '47'),
            array('daira_id' => '514', 'daira_nom' => 'LARBAA NATH IRATEN', 'wilaya_id' => '47'),
            array('daira_id' => '515', 'daira_nom' => 'MAATKAS', 'wilaya_id' => '47'),
            array('daira_id' => '516', 'daira_nom' => 'MAKOUDA', 'wilaya_id' => '47'),
            array('daira_id' => '517', 'daira_nom' => 'MEKLA', 'wilaya_id' => '47'),
            array('daira_id' => '518', 'daira_nom' => 'OUACIF', 'wilaya_id' => '47'),
            array('daira_id' => '519', 'daira_nom' => 'OUADHIAS', 'wilaya_id' => '47'),
            array('daira_id' => '520', 'daira_nom' => 'OUAGUENOUN', 'wilaya_id' => '47'),
            array('daira_id' => '521', 'daira_nom' => 'TIGZIRT', 'wilaya_id' => '47'),
            array('daira_id' => '522', 'daira_nom' => 'TIZI OUZOU', 'wilaya_id' => '47'),
            array('daira_id' => '523', 'daira_nom' => 'TIZI RACHED', 'wilaya_id' => '47'),
            array('daira_id' => '524', 'daira_nom' => 'TIZI-GHENIF', 'wilaya_id' => '47'),
            array('daira_id' => '525', 'daira_nom' => 'AIN TELLOUT', 'wilaya_id' => '48'),
            array('daira_id' => '526', 'daira_nom' => 'BAB EL ASSA', 'wilaya_id' => '48'),
            array('daira_id' => '527', 'daira_nom' => 'BENI BOUSSAID', 'wilaya_id' => '48'),
            array('daira_id' => '528', 'daira_nom' => 'BENI SNOUS', 'wilaya_id' => '48'),
            array('daira_id' => '529', 'daira_nom' => 'BENSEKRANE', 'wilaya_id' => '48'),
            array('daira_id' => '530', 'daira_nom' => 'CHETOUANE', 'wilaya_id' => '48'),
            array('daira_id' => '531', 'daira_nom' => 'FELLAOUCENE', 'wilaya_id' => '48'),
            array('daira_id' => '532', 'daira_nom' => 'GHAZAOUET', 'wilaya_id' => '48'),
            array('daira_id' => '533', 'daira_nom' => 'HENNAYA', 'wilaya_id' => '48'),
            array('daira_id' => '534', 'daira_nom' => 'HONNAINE', 'wilaya_id' => '48'),
            array('daira_id' => '535', 'daira_nom' => 'MAGHNIA', 'wilaya_id' => '48'),
            array('daira_id' => '536', 'daira_nom' => 'MANSOURAH', 'wilaya_id' => '48'),
            array('daira_id' => '537', 'daira_nom' => 'MARSA BEN MEHDI', 'wilaya_id' => '48'),
            array('daira_id' => '538', 'daira_nom' => 'NEDROMA', 'wilaya_id' => '48'),
            array('daira_id' => '539', 'daira_nom' => 'OULED MIMOUN', 'wilaya_id' => '48'),
            array('daira_id' => '540', 'daira_nom' => 'REMCHI', 'wilaya_id' => '48'),
            array('daira_id' => '541', 'daira_nom' => 'SABRA', 'wilaya_id' => '48'),
            array('daira_id' => '542', 'daira_nom' => 'SEBDOU', 'wilaya_id' => '48'),
            array('daira_id' => '543', 'daira_nom' => 'SIDI DJILLALI', 'wilaya_id' => '48'),
            array('daira_id' => '544', 'daira_nom' => 'TLEMCEN', 'wilaya_id' => '48')
        );

        DB::table('daira')->insert($daira);
    }
}
