<?php

use Illuminate\Database\Seeder;

class PieceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $piece = array(
            array('piece_id' => '1', 'piece_nom' => 'ATTELAGE', 'cat_id' => '1'),
            array('piece_id' => '2', 'piece_nom' => 'BOITIER ACCROCHAGE', 'cat_id' => '1'),
            array('piece_id' => '3', 'piece_nom' => 'BOULE ATTELAGE', 'cat_id' => '1'),
            array('piece_id' => '4', 'piece_nom' => 'FAISCEAU ATTELAGE', 'cat_id' => '1'),
            array('piece_id' => '5', 'piece_nom' => 'KIT ECLAIRAGE REMORQUE', 'cat_id' => '1'),
            array('piece_id' => '6', 'piece_nom' => 'PRISE MALE', 'cat_id' => '1'),
            array('piece_id' => '7', 'piece_nom' => 'SUPPORT ATTELAGE', 'cat_id' => '1'),
            array('piece_id' => '8', 'piece_nom' => 'BOITE A VITESSE AUTOMATIQUE', 'cat_id' => '2'),
            array('piece_id' => '9', 'piece_nom' => 'BOITE A VITESSE MECANIQUE', 'cat_id' => '2'),
            array('piece_id' => '10', 'piece_nom' => 'BOITE DE TRANSFERT', 'cat_id' => '2'),
            array('piece_id' => '11', 'piece_nom' => 'BOITIER DE COMMANDE BV AUTO', 'cat_id' => '2'),
            array('piece_id' => '12', 'piece_nom' => 'CALCULATEUR BOITE AUTO', 'cat_id' => '2'),
            array('piece_id' => '13', 'piece_nom' => 'CONTACTEUR FEUX RECUL', 'cat_id' => '2'),
            array('piece_id' => '14', 'piece_nom' => 'ECHANGEUR REFROID HUILE BOITE', 'cat_id' => '2'),
            array('piece_id' => '15', 'piece_nom' => 'LEVIER DE VITESSES', 'cat_id' => '2'),
            array('piece_id' => '16', 'piece_nom' => 'POMMEAU LEVIER VITESSES', 'cat_id' => '2'),
            array('piece_id' => '17', 'piece_nom' => 'SELECTEUR DE VITESSE', 'cat_id' => '2'),
            array('piece_id' => '18', 'piece_nom' => 'TRINGLERIE BOITE', 'cat_id' => '2'),
            array('piece_id' => '19', 'piece_nom' => 'PONT ARRIERE', 'cat_id' => '2'),
            array('piece_id' => '20', 'piece_nom' => 'PONT AVANT', 'cat_id' => '2'),
            array('piece_id' => '21', 'piece_nom' => 'FLECTOR', 'cat_id' => '2'),
            array('piece_id' => '22', 'piece_nom' => 'TRANSMISSION ARD', 'cat_id' => '2'),
            array('piece_id' => '23', 'piece_nom' => 'TRANSMISSION ARG', 'cat_id' => '2'),
            array('piece_id' => '24', 'piece_nom' => 'TRANSMISSION AVD', 'cat_id' => '2'),
            array('piece_id' => '25', 'piece_nom' => 'TRANSMISSION AVG', 'cat_id' => '2'),
            array('piece_id' => '26', 'piece_nom' => 'TRANSMISSION LONGITUDINALE', 'cat_id' => '2'),
            array('piece_id' => '27', 'piece_nom' => 'TRANSMISSION LONGITUDINALE AR', 'cat_id' => '2'),
            array('piece_id' => '28', 'piece_nom' => 'TRANSMISSION LONGITUDINALE AV', 'cat_id' => '2'),
            array('piece_id' => '29', 'piece_nom' => 'TRANSMISSION LONGITUDINALE CENT', 'cat_id' => '2'),
            array('piece_id' => '30', 'piece_nom' => 'CAISSE', 'cat_id' => '3'),
            array('piece_id' => '31', 'piece_nom' => 'ANTIVOL DE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '32', 'piece_nom' => 'BOITIER DE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '33', 'piece_nom' => 'CALCULATEUR DIRECTION ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '34', 'piece_nom' => 'COLONNE DE DIRECTION ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '35', 'piece_nom' => 'COLONNE DE DIRECTION NON ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '36', 'piece_nom' => 'CREMAILLERE', 'cat_id' => '4'),
            array('piece_id' => '37', 'piece_nom' => 'CREMAILLERE HYDRAULIQUE', 'cat_id' => '4'),
            array('piece_id' => '38', 'piece_nom' => 'CREMAILLERE NON ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '39', 'piece_nom' => 'KIT SERRURES + ANTIVOL', 'cat_id' => '4'),
            array('piece_id' => '40', 'piece_nom' => 'LECTEUR DE CARTE', 'cat_id' => '4'),
            array('piece_id' => '41', 'piece_nom' => 'MOTEUR ELECTRIQUE DA', 'cat_id' => '4'),
            array('piece_id' => '42', 'piece_nom' => 'POMPE DIRECTION ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '43', 'piece_nom' => 'POULIE POMPE DIREC ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '44', 'piece_nom' => 'RELAIS DE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '45', 'piece_nom' => 'VERIN DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '46', 'piece_nom' => 'VOLANT DE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '47', 'piece_nom' => 'CARDAN DE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '48', 'piece_nom' => 'COQUILLE DE VOLANT', 'cat_id' => '4'),
            array('piece_id' => '49', 'piece_nom' => 'FLEXIBLE DIRECTION ASSISTEE', 'cat_id' => '4'),
            array('piece_id' => '50', 'piece_nom' => 'RESERVOIR POMPE DIRECTION', 'cat_id' => '4'),
            array('piece_id' => '51', 'piece_nom' => 'ROTULE DE DIRECTION DROITE', 'cat_id' => '4'),
            array('piece_id' => '52', 'piece_nom' => 'ROTULE DE DIRECTION GAUCHE', 'cat_id' => '4'),
            array('piece_id' => '53', 'piece_nom' => 'COLLECTEUR ADMISSION', 'cat_id' => '5'),
            array('piece_id' => '54', 'piece_nom' => 'COLLECTEUR ECHAPPEMENT', 'cat_id' => '5'),
            array('piece_id' => '55', 'piece_nom' => 'CATALYSEUR', 'cat_id' => '5'),
            array('piece_id' => '56', 'piece_nom' => 'FLEXIBLE ECHAPPEMENT AV', 'cat_id' => '5'),
            array('piece_id' => '57', 'piece_nom' => 'PRECATALYSEUR', 'cat_id' => '5'),
            array('piece_id' => '58', 'piece_nom' => 'SILENCIEUX AR', 'cat_id' => '5'),
            array('piece_id' => '59', 'piece_nom' => 'SILENCIEUX AVANT', 'cat_id' => '5'),
            array('piece_id' => '60', 'piece_nom' => 'SILENCIEUX INTERMEDIAIRE', 'cat_id' => '5'),
            array('piece_id' => '61', 'piece_nom' => 'SONDE LAMBDA', 'cat_id' => '5'),
            array('piece_id' => '62', 'piece_nom' => 'TUBE ECHAPPEMENT', 'cat_id' => '5'),
            array('piece_id' => '63', 'piece_nom' => 'COLLIER ECHAPPEMENT', 'cat_id' => '5'),
            array('piece_id' => '64', 'piece_nom' => 'MANCHON', 'cat_id' => '5'),
            array('piece_id' => '65', 'piece_nom' => 'SILENTBLOC ECHAPPEMENT', 'cat_id' => '5'),
            array('piece_id' => '66', 'piece_nom' => 'SUPPORT ECHAP', 'cat_id' => '5'),
            array('piece_id' => '67', 'piece_nom' => 'ECLAIREUR PLAQUE DE POLICE', 'cat_id' => '6'),
            array('piece_id' => '68', 'piece_nom' => 'ECLAIREUR PLAQUE DE POLICE D', 'cat_id' => '6'),
            array('piece_id' => '69', 'piece_nom' => 'ECLAIREUR PLAQUE DE POLICE G', 'cat_id' => '6'),
            array('piece_id' => '70', 'piece_nom' => 'ECRAN FEU ARD', 'cat_id' => '6'),
            array('piece_id' => '71', 'piece_nom' => 'ECRAN FEU ARG', 'cat_id' => '6'),
            array('piece_id' => '72', 'piece_nom' => 'ENJOLIVEUR INF FEU AR D', 'cat_id' => '6'),
            array('piece_id' => '73', 'piece_nom' => 'ENJOLIVEUR INF FEU AR G', 'cat_id' => '6'),
            array('piece_id' => '74', 'piece_nom' => 'FEU AR INT D', 'cat_id' => '6'),
            array('piece_id' => '75', 'piece_nom' => 'FEU AR INT G', 'cat_id' => '6'),
            array('piece_id' => '76', 'piece_nom' => 'FEU ARD', 'cat_id' => '6'),
            array('piece_id' => '77', 'piece_nom' => 'FEU ARG', 'cat_id' => '6'),
            array('piece_id' => '78', 'piece_nom' => 'FEU BROUILLARD ARD', 'cat_id' => '6'),
            array('piece_id' => '79', 'piece_nom' => 'FEU BROUILLARD ARG', 'cat_id' => '6'),
            array('piece_id' => '80', 'piece_nom' => 'FEU BROUILLARD CENTRAL AR', 'cat_id' => '6'),
            array('piece_id' => '81', 'piece_nom' => 'FEU DE PARE-CHOC  ARD', 'cat_id' => '6'),
            array('piece_id' => '82', 'piece_nom' => 'FEU DE PARE-CHOC  ARG', 'cat_id' => '6'),
            array('piece_id' => '83', 'piece_nom' => 'FEU RECUL', 'cat_id' => '6'),
            array('piece_id' => '84', 'piece_nom' => 'FEU RECUL D', 'cat_id' => '6'),
            array('piece_id' => '85', 'piece_nom' => 'FEU RECUL G', 'cat_id' => '6'),
            array('piece_id' => '86', 'piece_nom' => 'FEUX STOP SUPPLEMENTAIRE', 'cat_id' => '6'),
            array('piece_id' => '87', 'piece_nom' => 'KIT FEU ARD', 'cat_id' => '6'),
            array('piece_id' => '88', 'piece_nom' => 'KIT FEU ARG', 'cat_id' => '6'),
            array('piece_id' => '89', 'piece_nom' => 'AMPOULE XENON', 'cat_id' => '6'),
            array('piece_id' => '90', 'piece_nom' => 'BOITIER XENON PHARE D', 'cat_id' => '6'),
            array('piece_id' => '91', 'piece_nom' => 'BOITIER XENON PHARE G', 'cat_id' => '6'),
            array('piece_id' => '92', 'piece_nom' => 'BOITIERS PHARE ANTIBROUILLARD D', 'cat_id' => '6'),
            array('piece_id' => '93', 'piece_nom' => 'BOITIERS PHARE ANTIBROUILLARD G', 'cat_id' => '6'),
            array('piece_id' => '94', 'piece_nom' => 'CLIGNOTANT D', 'cat_id' => '6'),
            array('piece_id' => '95', 'piece_nom' => 'CLIGNOTANT G', 'cat_id' => '6'),
            array('piece_id' => '96', 'piece_nom' => 'ENJOLIVEUR PHARE D', 'cat_id' => '6'),
            array('piece_id' => '97', 'piece_nom' => 'ENJOLIVEUR PHARE G', 'cat_id' => '6'),
            array('piece_id' => '98', 'piece_nom' => 'FEUX AV D', 'cat_id' => '6'),
            array('piece_id' => '99', 'piece_nom' => 'FEUX AV G', 'cat_id' => '6'),
            array('piece_id' => '100', 'piece_nom' => 'FEUX FACTICE D', 'cat_id' => '6'),
            array('piece_id' => '101', 'piece_nom' => 'FEUX FACTICE G', 'cat_id' => '6'),
            array('piece_id' => '102', 'piece_nom' => 'FEUX POSITION D', 'cat_id' => '6'),
            array('piece_id' => '103', 'piece_nom' => 'FEUX POSITION G', 'cat_id' => '6'),
            array('piece_id' => '104', 'piece_nom' => 'GLACE PHARE D', 'cat_id' => '6'),
            array('piece_id' => '105', 'piece_nom' => 'GLACE PHARE G', 'cat_id' => '6'),
            array('piece_id' => '106', 'piece_nom' => 'JEU BOITIERS PHARE ANTIBROUILLARD', 'cat_id' => '6'),
            array('piece_id' => '107', 'piece_nom' => 'JEU PHARES ANTIBROUILLARD', 'cat_id' => '6'),
            array('piece_id' => '108', 'piece_nom' => 'MOTEUR ESSUIE-PHARE D', 'cat_id' => '6'),
            array('piece_id' => '109', 'piece_nom' => 'MOTEUR ESSUIE-PHARE G', 'cat_id' => '6'),
            array('piece_id' => '110', 'piece_nom' => 'PHARE ANTIBROUILLARD AVD', 'cat_id' => '6'),
            array('piece_id' => '111', 'piece_nom' => 'PHARE ANTIBROUILLARD AVG', 'cat_id' => '6'),
            array('piece_id' => '112', 'piece_nom' => 'PHARE D', 'cat_id' => '6'),
            array('piece_id' => '113', 'piece_nom' => 'PHARE G', 'cat_id' => '6'),
            array('piece_id' => '114', 'piece_nom' => 'PHARE LONGUE PORTEE AVD', 'cat_id' => '6'),
            array('piece_id' => '115', 'piece_nom' => 'PHARE LONGUE PORTEE AVG', 'cat_id' => '6'),
            array('piece_id' => '116', 'piece_nom' => 'REPETITEUR AILE D', 'cat_id' => '6'),
            array('piece_id' => '117', 'piece_nom' => 'REPETITEUR AILE G', 'cat_id' => '6'),
            array('piece_id' => '118', 'piece_nom' => 'SUPPORT PHARE D', 'cat_id' => '6'),
            array('piece_id' => '119', 'piece_nom' => 'SUPPORT PHARE G', 'cat_id' => '6'),
            array('piece_id' => '120', 'piece_nom' => 'BOITE A FUSIBLES', 'cat_id' => '7'),
            array('piece_id' => '121', 'piece_nom' => 'PLATINE FUSIBLE AR', 'cat_id' => '7'),
            array('piece_id' => '122', 'piece_nom' => 'PLATINE FUSIBLE AV', 'cat_id' => '7'),
            array('piece_id' => '123', 'piece_nom' => 'PLATINE FUSIBLE HABITACLE', 'cat_id' => '7'),
            array('piece_id' => '124', 'piece_nom' => 'ALLUMEUR', 'cat_id' => '7'),
            array('piece_id' => '125', 'piece_nom' => 'BOBINE ALLUMAGE', 'cat_id' => '7'),
            array('piece_id' => '126', 'piece_nom' => 'BOITIER ALLUMAGE', 'cat_id' => '7'),
            array('piece_id' => '127', 'piece_nom' => 'DISTRIBUTEUR ALLUMAGE', 'cat_id' => '7'),
            array('piece_id' => '128', 'piece_nom' => 'MODULE ALLUMAGE', 'cat_id' => '7'),
            array('piece_id' => '129', 'piece_nom' => 'TETE ALLUMEUR', 'cat_id' => '7'),
            array('piece_id' => '130', 'piece_nom' => 'ALTERNATEUR', 'cat_id' => '7'),
            array('piece_id' => '131', 'piece_nom' => 'SUPPORT ALTERNATEUR', 'cat_id' => '7'),
            array('piece_id' => '132', 'piece_nom' => 'KLAXON  / AVERTISSEUR', 'cat_id' => '7'),
            array('piece_id' => '133', 'piece_nom' => 'BATTERIE', 'cat_id' => '7'),
            array('piece_id' => '134', 'piece_nom' => 'DEMARREUR', 'cat_id' => '7'),
            array('piece_id' => '135', 'piece_nom' => 'FAISCEAU AVANT', 'cat_id' => '7'),
            array('piece_id' => '136', 'piece_nom' => 'FAISCEAU ELECTRIQUE CHAUFFAGE', 'cat_id' => '7'),
            array('piece_id' => '137', 'piece_nom' => 'FAISCEAU MOTEUR', 'cat_id' => '7'),
            array('piece_id' => '138', 'piece_nom' => 'FAISCEAU TABLEAU DE BORD', 'cat_id' => '7'),
            array('piece_id' => '139', 'piece_nom' => 'BOITIER DE PRECHAUFFAGE', 'cat_id' => '7'),
            array('piece_id' => '140', 'piece_nom' => 'BOUGIE PRECHAUFFAGE', 'cat_id' => '7'),
            array('piece_id' => '141', 'piece_nom' => 'BUTEE EMBRAYAGE HYDRAULIQUE', 'cat_id' => '8'),
            array('piece_id' => '142', 'piece_nom' => 'CABLE EMBRAYAGE', 'cat_id' => '8'),
            array('piece_id' => '143', 'piece_nom' => 'CONVERTISSEUR', 'cat_id' => '8'),
            array('piece_id' => '144', 'piece_nom' => 'EMETTEUR EMBRAYAGE', 'cat_id' => '8'),
            array('piece_id' => '145', 'piece_nom' => 'KIT EMBRAYAGE', 'cat_id' => '8'),
            array('piece_id' => '146', 'piece_nom' => 'PEDALE EMBRAYAGE', 'cat_id' => '8'),
            array('piece_id' => '147', 'piece_nom' => 'RECEPTEUR EMBRAYAGE', 'cat_id' => '8'),
            array('piece_id' => '148', 'piece_nom' => 'ALLUME CIGARE', 'cat_id' => '9'),
            array('piece_id' => '149', 'piece_nom' => 'AUTORADIO', 'cat_id' => '9'),
            array('piece_id' => '150', 'piece_nom' => 'CENDRIER', 'cat_id' => '9'),
            array('piece_id' => '151', 'piece_nom' => 'MONTRE', 'cat_id' => '9'),
            array('piece_id' => '152', 'piece_nom' => 'TAPIS DE SOL', 'cat_id' => '9'),
            array('piece_id' => '153', 'piece_nom' => 'BALAIS ESSUIE-GLACE', 'cat_id' => '10'),
            array('piece_id' => '154', 'piece_nom' => 'BRAS ESSUIE-GLACE AR', 'cat_id' => '10'),
            array('piece_id' => '155', 'piece_nom' => 'BRAS ESSUIE-GLACE AV', 'cat_id' => '10'),
            array('piece_id' => '156', 'piece_nom' => 'BRAS ESSUIE-GLACE AVD', 'cat_id' => '10'),
            array('piece_id' => '157', 'piece_nom' => 'BRAS ESSUIE-GLACE AVG', 'cat_id' => '10'),
            array('piece_id' => '158', 'piece_nom' => 'CAPTEUR DE PLUIE', 'cat_id' => '10'),
            array('piece_id' => '159', 'piece_nom' => 'POMPE LAVE-GLACE AR', 'cat_id' => '10'),
            array('piece_id' => '160', 'piece_nom' => 'POMPE LAVE-GLACE AV', 'cat_id' => '10'),
            array('piece_id' => '161', 'piece_nom' => 'RESERVOIR LAVE-GLACE AR', 'cat_id' => '10'),
            array('piece_id' => '162', 'piece_nom' => 'RESERVOIR LAVE-GLACE AV', 'cat_id' => '10'),
            array('piece_id' => '163', 'piece_nom' => 'MECANISME ESSUIE-GLACE AR', 'cat_id' => '10'),
            array('piece_id' => '164', 'piece_nom' => 'MECANISME ESSUIE-GLACE AV', 'cat_id' => '10'),
            array('piece_id' => '165', 'piece_nom' => 'MOTEUR ESSUIE-GLACE AR', 'cat_id' => '10'),
            array('piece_id' => '166', 'piece_nom' => 'MOTEUR ESSUIE-GLACE AV', 'cat_id' => '10'),
            array('piece_id' => '167', 'piece_nom' => 'BLOC REGULATEUR', 'cat_id' => '11'),
            array('piece_id' => '168', 'piece_nom' => 'CALCULATEUR ABS', 'cat_id' => '11'),
            array('piece_id' => '169', 'piece_nom' => 'CAPTEUR ABS ARD', 'cat_id' => '11'),
            array('piece_id' => '170', 'piece_nom' => 'CAPTEUR ABS ARG', 'cat_id' => '11'),
            array('piece_id' => '171', 'piece_nom' => 'CAPTEUR ABS AVD', 'cat_id' => '11'),
            array('piece_id' => '172', 'piece_nom' => 'CAPTEUR ABS AVG', 'cat_id' => '11'),
            array('piece_id' => '173', 'piece_nom' => 'UNITE HYDRAULIQUE ABS', 'cat_id' => '11'),
            array('piece_id' => '174', 'piece_nom' => 'LEVIER FREIN A MAIN', 'cat_id' => '11'),
            array('piece_id' => '175', 'piece_nom' => 'PEDALE DE FREIN', 'cat_id' => '11'),
            array('piece_id' => '176', 'piece_nom' => 'PEDALIER COMPLET', 'cat_id' => '11'),
            array('piece_id' => '177', 'piece_nom' => 'BOCAL LIQUIDE FREIN', 'cat_id' => '11'),
            array('piece_id' => '178', 'piece_nom' => 'LIMITEUR/REPARTITEUR DE PRESSION ARRIERE', 'cat_id' => '11'),
            array('piece_id' => '179', 'piece_nom' => 'MAITRE CYLINDRE', 'cat_id' => '11'),
            array('piece_id' => '180', 'piece_nom' => 'POMPE A VIDE', 'cat_id' => '11'),
            array('piece_id' => '181', 'piece_nom' => 'SERVO-FREIN', 'cat_id' => '11'),
            array('piece_id' => '182', 'piece_nom' => 'BOITIER SUSPENSION HYDRACTIVE', 'cat_id' => '11'),
            array('piece_id' => '183', 'piece_nom' => 'CONJONCTEUR', 'cat_id' => '11'),
            array('piece_id' => '184', 'piece_nom' => 'CORRECTEUR DE HAUTEUR AR', 'cat_id' => '11'),
            array('piece_id' => '185', 'piece_nom' => 'CORRECTEUR DE HAUTEUR AV', 'cat_id' => '11'),
            array('piece_id' => '186', 'piece_nom' => 'POMPE HYDRAULIQUE LHM', 'cat_id' => '11'),
            array('piece_id' => '187', 'piece_nom' => 'REGULATEUR DE RAIDEUR AR', 'cat_id' => '11'),
            array('piece_id' => '188', 'piece_nom' => 'RESERVOIR LHM', 'cat_id' => '11'),
            array('piece_id' => '189', 'piece_nom' => 'DISQUE ARRIERE', 'cat_id' => '11'),
            array('piece_id' => '190', 'piece_nom' => 'DISQUE AVANT', 'cat_id' => '11'),
            array('piece_id' => '191', 'piece_nom' => 'ETRIER DE FREIN ARD', 'cat_id' => '11'),
            array('piece_id' => '192', 'piece_nom' => 'ETRIER DE FREIN ARG', 'cat_id' => '11'),
            array('piece_id' => '193', 'piece_nom' => 'ETRIER DE FREIN AVD', 'cat_id' => '11'),
            array('piece_id' => '194', 'piece_nom' => 'ETRIER DE FREIN AVG', 'cat_id' => '11'),
            array('piece_id' => '195', 'piece_nom' => 'FLASQUE ARD', 'cat_id' => '11'),
            array('piece_id' => '196', 'piece_nom' => 'FLASQUE ARG', 'cat_id' => '11'),
            array('piece_id' => '197', 'piece_nom' => 'TAMBOUR ARD', 'cat_id' => '11'),
            array('piece_id' => '198', 'piece_nom' => 'TAMBOUR ARG', 'cat_id' => '11'),
            array('piece_id' => '199', 'piece_nom' => 'BANQUETTE AR SUPL-7PLACES', 'cat_id' => '12'),
            array('piece_id' => '200', 'piece_nom' => 'KIT BANQUETTE ARRIERE COMPLETE', 'cat_id' => '12'),
            array('piece_id' => '201', 'piece_nom' => 'SIEGE AR COMPLET', 'cat_id' => '12'),
            array('piece_id' => '202', 'piece_nom' => 'SIEGE ARD', 'cat_id' => '12'),
            array('piece_id' => '203', 'piece_nom' => 'SIEGE ARG', 'cat_id' => '12'),
            array('piece_id' => '204', 'piece_nom' => 'SIEGE ARRIERE CENTRAL', 'cat_id' => '12'),
            array('piece_id' => '205', 'piece_nom' => 'SIEGE SUPPLEMENTAIRE ARD', 'cat_id' => '12'),
            array('piece_id' => '206', 'piece_nom' => 'SIEGE SUPPLEMENTAIRE ARG', 'cat_id' => '12'),
            array('piece_id' => '207', 'piece_nom' => 'SIEGE SUPPLEMENTAIRE CENTRAL', 'cat_id' => '12'),
            array('piece_id' => '208', 'piece_nom' => 'APPUI TETE AV', 'cat_id' => '12'),
            array('piece_id' => '209', 'piece_nom' => 'BANQUETTE AVANT', 'cat_id' => '12'),
            array('piece_id' => '210', 'piece_nom' => 'SIEGE AVANT CENTRAL', 'cat_id' => '12'),
            array('piece_id' => '211', 'piece_nom' => 'SIEGE AVD', 'cat_id' => '12'),
            array('piece_id' => '212', 'piece_nom' => 'SIEGE AVG', 'cat_id' => '12'),
            array('piece_id' => '213', 'piece_nom' => 'INTERIEUR COMPLET', 'cat_id' => '12'),
            array('piece_id' => '214', 'piece_nom' => 'BARRE DE TOIT', 'cat_id' => '13'),
            array('piece_id' => '215', 'piece_nom' => 'GARNITURE PAVILLON', 'cat_id' => '13'),
            array('piece_id' => '216', 'piece_nom' => 'PARE-SOLEIL DROIT', 'cat_id' => '13'),
            array('piece_id' => '217', 'piece_nom' => 'PARE-SOLEIL GAUCHE', 'cat_id' => '13'),
            array('piece_id' => '218', 'piece_nom' => 'PLAFONNIER', 'cat_id' => '13'),
            array('piece_id' => '219', 'piece_nom' => 'POIGNEE DE MAINTIEN', 'cat_id' => '13'),
            array('piece_id' => '220', 'piece_nom' => 'RETROVISEUR INTERIEUR', 'cat_id' => '13'),
            array('piece_id' => '221', 'piece_nom' => 'VIDE POCHE', 'cat_id' => '13'),
            array('piece_id' => '222', 'piece_nom' => 'BOITIER FILTRE A AIR', 'cat_id' => '14'),
            array('piece_id' => '223', 'piece_nom' => 'CARBURATEUR', 'cat_id' => '14'),
            array('piece_id' => '224', 'piece_nom' => 'POMPE A CARBURANT ELECTRIQUE', 'cat_id' => '14'),
            array('piece_id' => '225', 'piece_nom' => 'POMPE ALIMENTATION CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '226', 'piece_nom' => 'ACTUATEUR DE RALENTI', 'cat_id' => '14'),
            array('piece_id' => '227', 'piece_nom' => 'BLOC MONOPOINT', 'cat_id' => '14'),
            array('piece_id' => '228', 'piece_nom' => 'BOITIER INJECTION', 'cat_id' => '14'),
            array('piece_id' => '229', 'piece_nom' => 'BOITIER PAPILLON', 'cat_id' => '14'),
            array('piece_id' => '230', 'piece_nom' => 'CALCULATEUR MOTEUR', 'cat_id' => '14'),
            array('piece_id' => '231', 'piece_nom' => 'CAPTEUR PEDALE ACCELERATEUR', 'cat_id' => '14'),
            array('piece_id' => '232', 'piece_nom' => 'CAPTEUR PMH', 'cat_id' => '14'),
            array('piece_id' => '233', 'piece_nom' => 'DEBIMETRE AIR', 'cat_id' => '14'),
            array('piece_id' => '234', 'piece_nom' => 'DISTRIBUTEUR INJECTION', 'cat_id' => '14'),
            array('piece_id' => '235', 'piece_nom' => 'ELECTROVANNE', 'cat_id' => '14'),
            array('piece_id' => '236', 'piece_nom' => 'ENSEMBLE INJECTEURS', 'cat_id' => '14'),
            array('piece_id' => '237', 'piece_nom' => 'INJECTEUR', 'cat_id' => '14'),
            array('piece_id' => '238', 'piece_nom' => 'PEDALE ACCELERATEUR', 'cat_id' => '14'),
            array('piece_id' => '239', 'piece_nom' => 'POMPE AMORCAGE GO', 'cat_id' => '14'),
            array('piece_id' => '240', 'piece_nom' => 'POMPE HP', 'cat_id' => '14'),
            array('piece_id' => '241', 'piece_nom' => 'POMPE INJECTION DIESEL', 'cat_id' => '14'),
            array('piece_id' => '242', 'piece_nom' => 'POTENTIOMETRE ACCELERATEUR', 'cat_id' => '14'),
            array('piece_id' => '243', 'piece_nom' => 'POULIE CRANTEE POMPE INJECTION', 'cat_id' => '14'),
            array('piece_id' => '244', 'piece_nom' => 'RAMPE INJECTION', 'cat_id' => '14'),
            array('piece_id' => '245', 'piece_nom' => 'SUPPORT DE FILTRE CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '246', 'piece_nom' => 'TUYAUX INJECTEURS', 'cat_id' => '14'),
            array('piece_id' => '247', 'piece_nom' => 'VANNE EGR', 'cat_id' => '14'),
            array('piece_id' => '248', 'piece_nom' => 'BOUCHON RESERVOIR A CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '249', 'piece_nom' => 'GOULOTTE CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '250', 'piece_nom' => 'JAUGE A CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '251', 'piece_nom' => 'POMPE CARBURANT IMMERGEE', 'cat_id' => '14'),
            array('piece_id' => '252', 'piece_nom' => 'REFROIDISSEUR CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '253', 'piece_nom' => 'RESERVOIR CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '254', 'piece_nom' => 'VOLET DE TRAPPE CARBURANT', 'cat_id' => '14'),
            array('piece_id' => '255', 'piece_nom' => 'COMPRESSEUR D AIR', 'cat_id' => '14'),
            array('piece_id' => '256', 'piece_nom' => 'ECHANGEUR AIR', 'cat_id' => '14'),
            array('piece_id' => '257', 'piece_nom' => 'TURBO', 'cat_id' => '14'),
            array('piece_id' => '258', 'piece_nom' => 'POULE DE VILBREQUIN', 'cat_id' => '15'),
            array('piece_id' => '259', 'piece_nom' => 'VILBREQUIN', 'cat_id' => '15'),
            array('piece_id' => '260', 'piece_nom' => 'VOLANT MOTEUR', 'cat_id' => '15'),
            array('piece_id' => '261', 'piece_nom' => 'BLOC EMBIELLE', 'cat_id' => '15'),
            array('piece_id' => '262', 'piece_nom' => 'BLOC MOTEUR NU', 'cat_id' => '15'),
            array('piece_id' => '263', 'piece_nom' => 'ARBRE A CAMES', 'cat_id' => '15'),
            array('piece_id' => '264', 'piece_nom' => 'COUVRE CULASSE', 'cat_id' => '15'),
            array('piece_id' => '265', 'piece_nom' => 'CULASSE DIESEL', 'cat_id' => '15'),
            array('piece_id' => '266', 'piece_nom' => 'CULASSE ESSENCE', 'cat_id' => '15'),
            array('piece_id' => '267', 'piece_nom' => 'POULIE ARBRE A CAMES', 'cat_id' => '15'),
            array('piece_id' => '268', 'piece_nom' => 'CARTER INF MOTEUR', 'cat_id' => '15'),
            array('piece_id' => '269', 'piece_nom' => 'JAUGE A HUILE', 'cat_id' => '15'),
            array('piece_id' => '270', 'piece_nom' => 'POMPE A HUILE', 'cat_id' => '15'),
            array('piece_id' => '271', 'piece_nom' => 'PROTECTION CARTER HUILE', 'cat_id' => '15'),
            array('piece_id' => '272', 'piece_nom' => 'PUITS DE JAUGE', 'cat_id' => '15'),
            array('piece_id' => '273', 'piece_nom' => 'REFROIDISSEUR  FILTRE A HUILE', 'cat_id' => '15'),
            array('piece_id' => '274', 'piece_nom' => 'SUPPORT FILTRE A HUILE', 'cat_id' => '15'),
            array('piece_id' => '275', 'piece_nom' => 'MOTEUR BOITE', 'cat_id' => '15'),
            array('piece_id' => '276', 'piece_nom' => 'MOTEUR BOITE COMPLET', 'cat_id' => '15'),
            array('piece_id' => '277', 'piece_nom' => 'MOTEUR COMPLET', 'cat_id' => '15'),
            array('piece_id' => '278', 'piece_nom' => 'MOTEUR DIESEL', 'cat_id' => '15'),
            array('piece_id' => '279', 'piece_nom' => 'MOTEUR ESSENCE', 'cat_id' => '15'),
            array('piece_id' => '280', 'piece_nom' => 'BIELLETTE ANTI-COUPLE MOTEUR', 'cat_id' => '15'),
            array('piece_id' => '281', 'piece_nom' => 'SUPPORT BOITE DE VITESSE', 'cat_id' => '15'),
            array('piece_id' => '282', 'piece_nom' => 'SUPPORT MOTEUR', 'cat_id' => '15'),
            array('piece_id' => '283', 'piece_nom' => 'ACTIONNEUR COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '284', 'piece_nom' => 'BARILLET COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '285', 'piece_nom' => 'COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '286', 'piece_nom' => 'COMPAS D COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '287', 'piece_nom' => 'COMPAS G COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '288', 'piece_nom' => 'DEFLECTEUR COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '289', 'piece_nom' => 'POIGNEE EXT COFFRE', 'cat_id' => '16'),
            array('piece_id' => '290', 'piece_nom' => 'SERRURE COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '291', 'piece_nom' => 'VERIN D COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '292', 'piece_nom' => 'VERIN G COFFRE AR', 'cat_id' => '16'),
            array('piece_id' => '293', 'piece_nom' => 'CACHE BAGAGE', 'cat_id' => '16'),
            array('piece_id' => '294', 'piece_nom' => 'GARNITURE PORTE LAT COULISSANTE', 'cat_id' => '16'),
            array('piece_id' => '295', 'piece_nom' => 'GARNITURE PORTE LAT COULISSANTE', 'cat_id' => '16'),
            array('piece_id' => '296', 'piece_nom' => 'SUPPORT D TABLETTE PLAGE AR', 'cat_id' => '16'),
            array('piece_id' => '297', 'piece_nom' => 'SUPPORT G TABLETTE PLAGE AR', 'cat_id' => '16'),
            array('piece_id' => '298', 'piece_nom' => 'TABLETTE PLAGE AR', 'cat_id' => '16'),
            array('piece_id' => '299', 'piece_nom' => 'ACTIONNEUR SERRURE HAYON', 'cat_id' => '16'),
            array('piece_id' => '300', 'piece_nom' => 'BECQUET HAYON', 'cat_id' => '16'),
            array('piece_id' => '301', 'piece_nom' => 'CHARNIERE D HAYON', 'cat_id' => '16'),
            array('piece_id' => '302', 'piece_nom' => 'CHARNIERE G HAYON', 'cat_id' => '16'),
            array('piece_id' => '303', 'piece_nom' => 'DEFLECTEUR HAYON', 'cat_id' => '16'),
            array('piece_id' => '304', 'piece_nom' => 'HAYON', 'cat_id' => '16'),
            array('piece_id' => '305', 'piece_nom' => 'HAYON INF', 'cat_id' => '16'),
            array('piece_id' => '306', 'piece_nom' => 'JEU CHARNIERE HAYON', 'cat_id' => '16'),
            array('piece_id' => '307', 'piece_nom' => 'POIGNEE EXT HAYON', 'cat_id' => '16'),
            array('piece_id' => '308', 'piece_nom' => 'PORTE CHARG.HAYON  AR (UTL)', 'cat_id' => '16'),
            array('piece_id' => '309', 'piece_nom' => 'PROTECTION HAYON', 'cat_id' => '16'),
            array('piece_id' => '310', 'piece_nom' => 'SERRURE HAYON', 'cat_id' => '16'),
            array('piece_id' => '311', 'piece_nom' => 'SOUBASSEMENT DE HAYON', 'cat_id' => '16'),
            array('piece_id' => '312', 'piece_nom' => 'VERIN D HAYON', 'cat_id' => '16'),
            array('piece_id' => '313', 'piece_nom' => 'VERIN G HAYON', 'cat_id' => '16'),
            array('piece_id' => '314', 'piece_nom' => 'VERIN GLACE HAYON', 'cat_id' => '16'),
            array('piece_id' => '315', 'piece_nom' => 'ABSORBEUR PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '316', 'piece_nom' => 'CAPTEUR AIDE STATIONNEMENT AR', 'cat_id' => '16'),
            array('piece_id' => '317', 'piece_nom' => 'COL DE CYGNE', 'cat_id' => '16'),
            array('piece_id' => '318', 'piece_nom' => 'CROSSE ARD', 'cat_id' => '16'),
            array('piece_id' => '319', 'piece_nom' => 'CROSSE ARG', 'cat_id' => '16'),
            array('piece_id' => '320', 'piece_nom' => 'ENJOLIVEUR PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '321', 'piece_nom' => 'GRILLE PARE CHOC-AR', 'cat_id' => '16'),
            array('piece_id' => '322', 'piece_nom' => 'JEU SUPPORTS PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '323', 'piece_nom' => 'OBTURATEUR PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '324', 'piece_nom' => 'PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '325', 'piece_nom' => 'PROTECTION D PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '326', 'piece_nom' => 'PROTECTION G PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '327', 'piece_nom' => 'PROTECTION PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '328', 'piece_nom' => 'RENFORT PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '329', 'piece_nom' => 'SPOILER AR', 'cat_id' => '16'),
            array('piece_id' => '330', 'piece_nom' => 'SUPPORT CENTRAL PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '331', 'piece_nom' => 'SUPPORT D PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '332', 'piece_nom' => 'SUPPORT G PARE-CHOC AR', 'cat_id' => '16'),
            array('piece_id' => '333', 'piece_nom' => 'CHARNIERE INF PORTE BATTANTE ARD', 'cat_id' => '16'),
            array('piece_id' => '334', 'piece_nom' => 'CHARNIERE INF PORTE BATTANTE ARG', 'cat_id' => '16'),
            array('piece_id' => '335', 'piece_nom' => 'CHARNIERE SUP PORTE BATTANTE ARD', 'cat_id' => '16'),
            array('piece_id' => '336', 'piece_nom' => 'CHARNIERE SUP PORTE BATTANTE ARG', 'cat_id' => '16'),
            array('piece_id' => '337', 'piece_nom' => 'GARNITURE PORTE BATTANTE AR', 'cat_id' => '16'),
            array('piece_id' => '338', 'piece_nom' => 'GARNITURE PORTE BATTANTE AR', 'cat_id' => '16'),
            array('piece_id' => '339', 'piece_nom' => 'POIGNEE EXT PORTE BATTANTE', 'cat_id' => '16'),
            array('piece_id' => '340', 'piece_nom' => 'POIGNEE EXT PORTE BATTANTE D', 'cat_id' => '16'),
            array('piece_id' => '341', 'piece_nom' => 'POIGNEE EXT PORTE BATTANTE G', 'cat_id' => '16'),
            array('piece_id' => '342', 'piece_nom' => 'PORTE BATTANTE AR', 'cat_id' => '16'),
            array('piece_id' => '343', 'piece_nom' => 'PORTE BATTANTE ARD', 'cat_id' => '16'),
            array('piece_id' => '344', 'piece_nom' => 'PORTE BATTANTE ARG', 'cat_id' => '16'),
            array('piece_id' => '345', 'piece_nom' => 'SERRURE PORTE BATTANTE AR', 'cat_id' => '16'),
            array('piece_id' => '346', 'piece_nom' => 'SERRURE PORTE BATTANTE ARD', 'cat_id' => '16'),
            array('piece_id' => '347', 'piece_nom' => 'SERRURE PORTE BATTANTE ARG', 'cat_id' => '16'),
            array('piece_id' => '348', 'piece_nom' => 'GIRAFON', 'cat_id' => '16'),
            array('piece_id' => '349', 'piece_nom' => 'RIDELLE AR', 'cat_id' => '16'),
            array('piece_id' => '350', 'piece_nom' => 'JUPE AR', 'cat_id' => '16'),
            array('piece_id' => '351', 'piece_nom' => 'KIT COMPLET AR SOCIETE', 'cat_id' => '16'),
            array('piece_id' => '352', 'piece_nom' => 'TRAVERSE AR', 'cat_id' => '16'),
            array('piece_id' => '353', 'piece_nom' => 'AILE AVD', 'cat_id' => '17'),
            array('piece_id' => '354', 'piece_nom' => 'AILE AVG', 'cat_id' => '17'),
            array('piece_id' => '355', 'piece_nom' => 'ELARGISSEUR AILE AVD', 'cat_id' => '17'),
            array('piece_id' => '356', 'piece_nom' => 'ELARGISSEUR AILE AVG', 'cat_id' => '17'),
            array('piece_id' => '357', 'piece_nom' => 'PARE-BOUE AVD', 'cat_id' => '17'),
            array('piece_id' => '358', 'piece_nom' => 'PARE-BOUE AVG', 'cat_id' => '17'),
            array('piece_id' => '359', 'piece_nom' => 'PROTECTION AILE AVD', 'cat_id' => '17'),
            array('piece_id' => '360', 'piece_nom' => 'PROTECTION AILE AVG', 'cat_id' => '17'),
            array('piece_id' => '361', 'piece_nom' => 'ARMATURE AV', 'cat_id' => '17'),
            array('piece_id' => '362', 'piece_nom' => 'FACE AVANT', 'cat_id' => '17'),
            array('piece_id' => '363', 'piece_nom' => 'PASSAGE ROUE AVD', 'cat_id' => '17'),
            array('piece_id' => '364', 'piece_nom' => 'PASSAGE ROUE AVG', 'cat_id' => '17'),
            array('piece_id' => '365', 'piece_nom' => 'TOLE FACE AVANT', 'cat_id' => '17'),
            array('piece_id' => '366', 'piece_nom' => 'TOLE PORTE PHARE D', 'cat_id' => '17'),
            array('piece_id' => '367', 'piece_nom' => 'TOLE PORTE PHARE G', 'cat_id' => '17'),
            array('piece_id' => '368', 'piece_nom' => 'TRAVERSE INF ARMATURE AV', 'cat_id' => '17'),
            array('piece_id' => '369', 'piece_nom' => 'TRAVERSE SUP ARMATURE AV', 'cat_id' => '17'),
            array('piece_id' => '370', 'piece_nom' => 'BAIE PARE BRISE', 'cat_id' => '17'),
            array('piece_id' => '371', 'piece_nom' => 'TOLE AUVENT PARE-BRISE', 'cat_id' => '17'),
            array('piece_id' => '372', 'piece_nom' => 'CALANDRE', 'cat_id' => '17'),
            array('piece_id' => '373', 'piece_nom' => 'ENJOLIVEUR CALANDRE', 'cat_id' => '17'),
            array('piece_id' => '374', 'piece_nom' => 'ENJOLIVEUR CALANDRE D', 'cat_id' => '17'),
            array('piece_id' => '375', 'piece_nom' => 'ENJOLIVEUR CALANDRE G', 'cat_id' => '17'),
            array('piece_id' => '376', 'piece_nom' => 'GRILLE CALANDRE', 'cat_id' => '17'),
            array('piece_id' => '377', 'piece_nom' => 'GRILLE CALANDRE D', 'cat_id' => '17'),
            array('piece_id' => '378', 'piece_nom' => 'GRILLE CALANDRE G', 'cat_id' => '17'),
            array('piece_id' => '379', 'piece_nom' => 'SIGLE CALANDRE', 'cat_id' => '17'),
            array('piece_id' => '380', 'piece_nom' => 'SUPPORT CALANDRE', 'cat_id' => '17'),
            array('piece_id' => '381', 'piece_nom' => 'SUPPORT CALANDRE D', 'cat_id' => '17'),
            array('piece_id' => '382', 'piece_nom' => 'SUPPORT CALANDRE G', 'cat_id' => '17'),
            array('piece_id' => '383', 'piece_nom' => 'BEQUILLE CAPOT', 'cat_id' => '17'),
            array('piece_id' => '384', 'piece_nom' => 'CAPOT', 'cat_id' => '17'),
            array('piece_id' => '385', 'piece_nom' => 'COMPAS D CAPOT', 'cat_id' => '17'),
            array('piece_id' => '386', 'piece_nom' => 'COMPAS G CAPOT', 'cat_id' => '17'),
            array('piece_id' => '387', 'piece_nom' => 'GRILLE CAPOT', 'cat_id' => '17'),
            array('piece_id' => '388', 'piece_nom' => 'GRILLE D CAPOT', 'cat_id' => '17'),
            array('piece_id' => '389', 'piece_nom' => 'GRILLE G CAPOT', 'cat_id' => '17'),
            array('piece_id' => '390', 'piece_nom' => 'JEU COMPAS CAPOT', 'cat_id' => '17'),
            array('piece_id' => '391', 'piece_nom' => 'JOINT CAPOT', 'cat_id' => '17'),
            array('piece_id' => '392', 'piece_nom' => 'SERRURE CAPOT', 'cat_id' => '17'),
            array('piece_id' => '393', 'piece_nom' => 'SIGLE CAPOT', 'cat_id' => '17'),
            array('piece_id' => '394', 'piece_nom' => 'VERIN D CAPOT', 'cat_id' => '17'),
            array('piece_id' => '395', 'piece_nom' => 'VERIN G CAPOT', 'cat_id' => '17'),
            array('piece_id' => '396', 'piece_nom' => 'ABSORBEUR PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '397', 'piece_nom' => 'CAPTEUR AIDE STATIONNEMENT AV', 'cat_id' => '17'),
            array('piece_id' => '398', 'piece_nom' => 'CROSSE D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '399', 'piece_nom' => 'CROSSE G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '400', 'piece_nom' => 'ENJOLIVEUR D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '401', 'piece_nom' => 'ENJOLIVEUR G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '402', 'piece_nom' => 'ENJOLIVEUR PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '403', 'piece_nom' => 'GRILLE D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '404', 'piece_nom' => 'GRILLE G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '405', 'piece_nom' => 'GRILLE PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '406', 'piece_nom' => 'JEU OBTURATEURS PHARES ADDIT.  PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '407', 'piece_nom' => 'JEU SUPPORTS PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '408', 'piece_nom' => 'JUPE AV', 'cat_id' => '17'),
            array('piece_id' => '409', 'piece_nom' => 'OBTURATEUR PHARE ADDITIONNEL D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '410', 'piece_nom' => 'OBTURATEUR PHARE ADDITIONNEL G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '411', 'piece_nom' => 'PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '412', 'piece_nom' => 'PROTECTION D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '413', 'piece_nom' => 'PROTECTION G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '414', 'piece_nom' => 'PROTECTION PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '415', 'piece_nom' => 'RENFORT D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '416', 'piece_nom' => 'RENFORT G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '417', 'piece_nom' => 'RENFORT PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '418', 'piece_nom' => 'SPOILER AV', 'cat_id' => '17'),
            array('piece_id' => '419', 'piece_nom' => 'SPOILER AVD', 'cat_id' => '17'),
            array('piece_id' => '420', 'piece_nom' => 'SPOILER AVG', 'cat_id' => '17'),
            array('piece_id' => '421', 'piece_nom' => 'SUPPORT CENTRAL PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '422', 'piece_nom' => 'SUPPORT D PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '423', 'piece_nom' => 'SUPPORT G PARE-CHOC AV', 'cat_id' => '17'),
            array('piece_id' => '424', 'piece_nom' => 'SUPPORT PLAQUE DE POLICE AV', 'cat_id' => '17'),
            array('piece_id' => '425', 'piece_nom' => 'ACTIONNEUR PORTILLON AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '426', 'piece_nom' => 'ACTIONNEUR PORTILLON AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '427', 'piece_nom' => 'AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '428', 'piece_nom' => 'AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '429', 'piece_nom' => 'ELARGISSEUR AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '430', 'piece_nom' => 'ELARGISSEUR AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '431', 'piece_nom' => 'ENJOLIVEUR AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '432', 'piece_nom' => 'ENJOLIVEUR AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '433', 'piece_nom' => 'MECANISME LEVE GLACE AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '434', 'piece_nom' => 'MECANISME LEVE GLACE AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '435', 'piece_nom' => 'MECANISME OUVERTURE GLACE CUSTODE ARD', 'cat_id' => '17'),
            array('piece_id' => '436', 'piece_nom' => 'MECANISME OUVERTURE GLACE CUSTODE ARG', 'cat_id' => '17'),
            array('piece_id' => '437', 'piece_nom' => 'MECANISME+MOTEUR LEVE GLACE AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '438', 'piece_nom' => 'MECANISME+MOTEUR LEVE GLACE AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '439', 'piece_nom' => 'MOTEUR LEVE GLACE AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '440', 'piece_nom' => 'MOTEUR LEVE GLACE AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '441', 'piece_nom' => 'PARE-BOUE ARD', 'cat_id' => '17'),
            array('piece_id' => '442', 'piece_nom' => 'PARE-BOUE ARG', 'cat_id' => '17'),
            array('piece_id' => '443', 'piece_nom' => 'PORTILLON CARBURANT AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '444', 'piece_nom' => 'PORTILLON CARBURANT AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '445', 'piece_nom' => 'PROTECTION AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '446', 'piece_nom' => 'PROTECTION AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '447', 'piece_nom' => 'TOLE FERMETURE INF AILE ARD', 'cat_id' => '17'),
            array('piece_id' => '448', 'piece_nom' => 'TOLE FERMETURE INF AILE ARG', 'cat_id' => '17'),
            array('piece_id' => '449', 'piece_nom' => 'BAS CAISSE D', 'cat_id' => '18'),
            array('piece_id' => '450', 'piece_nom' => 'BAS CAISSE G', 'cat_id' => '18'),
            array('piece_id' => '451', 'piece_nom' => 'ACTIONNEUR SERRURE PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '452', 'piece_nom' => 'ACTIONNEUR SERRURE PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '453', 'piece_nom' => 'COMMANDE LEVE-GLACE PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '454', 'piece_nom' => 'COMMANDE LEVE-GLACE PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '455', 'piece_nom' => 'CONTACTEUR PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '456', 'piece_nom' => 'CONTACTEUR PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '457', 'piece_nom' => 'GARNITURE PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '458', 'piece_nom' => 'GARNITURE PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '459', 'piece_nom' => 'MECANISME LEVE-GLACE ARD', 'cat_id' => '18'),
            array('piece_id' => '460', 'piece_nom' => 'MECANISME LEVE-GLACE ARG', 'cat_id' => '18'),
            array('piece_id' => '461', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE ARD', 'cat_id' => '18'),
            array('piece_id' => '462', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE ARG', 'cat_id' => '18'),
            array('piece_id' => '463', 'piece_nom' => 'POIGNEE EXT PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '464', 'piece_nom' => 'POIGNEE EXT PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '465', 'piece_nom' => 'POIGNEE INT PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '466', 'piece_nom' => 'POIGNEE INT PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '467', 'piece_nom' => 'PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '468', 'piece_nom' => 'PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '469', 'piece_nom' => 'PROTECTION PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '470', 'piece_nom' => 'PROTECTION PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '471', 'piece_nom' => 'SERRURE PORTE ARD', 'cat_id' => '18'),
            array('piece_id' => '472', 'piece_nom' => 'SERRURE PORTE ARG', 'cat_id' => '18'),
            array('piece_id' => '473', 'piece_nom' => 'SYSTEME CONDAMNATION ARD', 'cat_id' => '18'),
            array('piece_id' => '474', 'piece_nom' => 'SYSTEME CONDAMNATION ARG', 'cat_id' => '18'),
            array('piece_id' => '475', 'piece_nom' => 'ACTIONNEUR SERRURE PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '476', 'piece_nom' => 'ACTIONNEUR SERRURE PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '477', 'piece_nom' => 'BARILLET PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '478', 'piece_nom' => 'BARILLET PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '479', 'piece_nom' => 'BOITIER IMPULSION LEVE-GLACE', 'cat_id' => '18'),
            array('piece_id' => '480', 'piece_nom' => 'BOITIER VERROUILLAGE CENTRALISE PORTE', 'cat_id' => '18'),
            array('piece_id' => '481', 'piece_nom' => 'CARENAGE RETROVISEUR EXT D', 'cat_id' => '18'),
            array('piece_id' => '482', 'piece_nom' => 'CARENAGE RETROVISEUR EXT G', 'cat_id' => '18'),
            array('piece_id' => '483', 'piece_nom' => 'COMMANDE LEVE-GLACE PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '484', 'piece_nom' => 'COMMANDE LEVE-GLACE PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '485', 'piece_nom' => 'COMMANDE RETROVISSEUR EXT ELECTRIQUE', 'cat_id' => '18'),
            array('piece_id' => '486', 'piece_nom' => 'COMMANDE RETROVISSEUR EXT ELECTRIQUE D', 'cat_id' => '18'),
            array('piece_id' => '487', 'piece_nom' => 'COMMANDE RETROVISSEUR EXT ELECTRIQUE G', 'cat_id' => '18'),
            array('piece_id' => '488', 'piece_nom' => 'CONTACTEUR PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '489', 'piece_nom' => 'CONTACTEUR PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '490', 'piece_nom' => 'EMETTEUR/RECEPTEUR VERROUILLAGE CENTRALISE', 'cat_id' => '18'),
            array('piece_id' => '491', 'piece_nom' => 'GARNITURE PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '492', 'piece_nom' => 'GARNITURE PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '493', 'piece_nom' => 'GLACE  RETROVISEUR EXT D', 'cat_id' => '18'),
            array('piece_id' => '494', 'piece_nom' => 'GLACE  RETROVISEUR EXT G', 'cat_id' => '18'),
            array('piece_id' => '495', 'piece_nom' => 'JEU BARILLETS', 'cat_id' => '18'),
            array('piece_id' => '496', 'piece_nom' => 'JOINT PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '497', 'piece_nom' => 'JOINT PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '498', 'piece_nom' => 'MECANISME LEVE-GLACE AVD', 'cat_id' => '18'),
            array('piece_id' => '499', 'piece_nom' => 'MECANISME LEVE-GLACE AVG', 'cat_id' => '18'),
            array('piece_id' => '500', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE AVD', 'cat_id' => '18'),
            array('piece_id' => '501', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE AVG', 'cat_id' => '18'),
            array('piece_id' => '502', 'piece_nom' => 'POIGNEE EXT PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '503', 'piece_nom' => 'POIGNEE EXT PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '504', 'piece_nom' => 'POIGNEE INT PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '505', 'piece_nom' => 'POIGNEE INT PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '506', 'piece_nom' => 'POMPE VERROUILLAGE CENTRALISE', 'cat_id' => '18'),
            array('piece_id' => '507', 'piece_nom' => 'PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '508', 'piece_nom' => 'PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '509', 'piece_nom' => 'PROTECTION PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '510', 'piece_nom' => 'PROTECTION PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '511', 'piece_nom' => 'RETROVISEUR EXT ELECTRIQUE D', 'cat_id' => '18'),
            array('piece_id' => '512', 'piece_nom' => 'RETROVISEUR EXT ELECTRIQUE G', 'cat_id' => '18'),
            array('piece_id' => '513', 'piece_nom' => 'RETROVISEUR EXT. D', 'cat_id' => '18'),
            array('piece_id' => '514', 'piece_nom' => 'RETROVISEUR EXT. G', 'cat_id' => '18'),
            array('piece_id' => '515', 'piece_nom' => 'SERRURE PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '516', 'piece_nom' => 'SERRURE PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '517', 'piece_nom' => 'SYSTEME CONDAMNATION AVD', 'cat_id' => '18'),
            array('piece_id' => '518', 'piece_nom' => 'SYSTEME CONDAMNATION AVG', 'cat_id' => '18'),
            array('piece_id' => '519', 'piece_nom' => 'TIRANT PORTE AVD', 'cat_id' => '18'),
            array('piece_id' => '520', 'piece_nom' => 'TIRANT PORTE AVG', 'cat_id' => '18'),
            array('piece_id' => '521', 'piece_nom' => 'GARNITURE PORTE LAT COULISSANTE', 'cat_id' => '18'),
            array('piece_id' => '522', 'piece_nom' => 'GARNITURE PORTE LAT COULISSANTE', 'cat_id' => '18'),
            array('piece_id' => '523', 'piece_nom' => 'MECANISME LEVE-GLACE PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '524', 'piece_nom' => 'MECANISME LEVE-GLACE PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '525', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '526', 'piece_nom' => 'MECANISME+MOTEUR LEVE-GLACE PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '527', 'piece_nom' => 'POIGNEE EXT PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '528', 'piece_nom' => 'POIGNEE EXT PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '529', 'piece_nom' => 'POIGNEE INT PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '530', 'piece_nom' => 'POIGNEE INT PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '531', 'piece_nom' => 'PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '532', 'piece_nom' => 'PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '533', 'piece_nom' => 'SERRURE PORTE COULISSANTE D', 'cat_id' => '18'),
            array('piece_id' => '534', 'piece_nom' => 'SERRURE PORTE COULISSANTE G', 'cat_id' => '18'),
            array('piece_id' => '535', 'piece_nom' => 'CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '536', 'piece_nom' => 'COUVERCLE CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '537', 'piece_nom' => 'HARD-TOP', 'cat_id' => '19'),
            array('piece_id' => '538', 'piece_nom' => 'MECANISME+MOTEUR DEVERROUILLAGE CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '539', 'piece_nom' => 'VERIN D CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '540', 'piece_nom' => 'VERIN D COUVERCLE CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '541', 'piece_nom' => 'VERIN G CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '542', 'piece_nom' => 'VERIN G COUVERCLE CAPOTE', 'cat_id' => '19'),
            array('piece_id' => '543', 'piece_nom' => 'MOTEUR TOIT OUVRANT', 'cat_id' => '19'),
            array('piece_id' => '544', 'piece_nom' => 'TOIT OUVRANT', 'cat_id' => '19'),
            array('piece_id' => '545', 'piece_nom' => 'BAC ROUE DE SECOURS', 'cat_id' => '20'),
            array('piece_id' => '546', 'piece_nom' => 'CRIC', 'cat_id' => '20'),
            array('piece_id' => '547', 'piece_nom' => 'CRIC + MANIVELLE', 'cat_id' => '20'),
            array('piece_id' => '548', 'piece_nom' => 'ENJOLIVEUR DE ROUE', 'cat_id' => '20'),
            array('piece_id' => '549', 'piece_nom' => 'MANIVELLE DE CRIC', 'cat_id' => '20'),
            array('piece_id' => '550', 'piece_nom' => 'PANIER ROUE SECOURS', 'cat_id' => '20'),
            array('piece_id' => '551', 'piece_nom' => 'JANTE ALUMINIUM 1', 'cat_id' => '20'),
            array('piece_id' => '552', 'piece_nom' => 'JANTE ALUMINIUM 2', 'cat_id' => '20'),
            array('piece_id' => '553', 'piece_nom' => 'JANTE ALUMINIUM 3', 'cat_id' => '20'),
            array('piece_id' => '554', 'piece_nom' => 'JANTE ALUMINIUM 4', 'cat_id' => '20'),
            array('piece_id' => '555', 'piece_nom' => 'JANTE ALUMINIUM 5', 'cat_id' => '20'),
            array('piece_id' => '556', 'piece_nom' => 'JANTE TOLE 1', 'cat_id' => '20'),
            array('piece_id' => '557', 'piece_nom' => 'JANTE TOLE 2', 'cat_id' => '20'),
            array('piece_id' => '558', 'piece_nom' => 'JANTE TOLE 3', 'cat_id' => '20'),
            array('piece_id' => '559', 'piece_nom' => 'JANTE TOLE 4', 'cat_id' => '20'),
            array('piece_id' => '560', 'piece_nom' => 'JANTE TOLE 5', 'cat_id' => '20'),
            array('piece_id' => '561', 'piece_nom' => 'JANTE TOLE 6', 'cat_id' => '20'),
            array('piece_id' => '562', 'piece_nom' => 'PAIRE DE PNEUS', 'cat_id' => '20'),
            array('piece_id' => '563', 'piece_nom' => 'PNEUMATIQUES', 'cat_id' => '20'),
            array('piece_id' => '564', 'piece_nom' => 'ROUE COMPLETE', 'cat_id' => '20'),
            array('piece_id' => '565', 'piece_nom' => 'ROUE SECOURS', 'cat_id' => '20'),
            array('piece_id' => '566', 'piece_nom' => 'AIR BAG ASSISE ARD', 'cat_id' => '21'),
            array('piece_id' => '567', 'piece_nom' => 'AIR BAG ASSISE ARG', 'cat_id' => '21'),
            array('piece_id' => '568', 'piece_nom' => 'AIR BAG COLONNE DIRECTION', 'cat_id' => '21'),
            array('piece_id' => '569', 'piece_nom' => 'AIRBAG LATERAL ARD', 'cat_id' => '21'),
            array('piece_id' => '570', 'piece_nom' => 'AIRBAG LATERAL ARG', 'cat_id' => '21'),
            array('piece_id' => '571', 'piece_nom' => 'AIRBAG PORTE AVD', 'cat_id' => '21'),
            array('piece_id' => '572', 'piece_nom' => 'AIRBAG PORTE AVG', 'cat_id' => '21'),
            array('piece_id' => '573', 'piece_nom' => 'AIRBAG SIEGE AVD', 'cat_id' => '21'),
            array('piece_id' => '574', 'piece_nom' => 'AIRBAG SIEGE AVG', 'cat_id' => '21'),
            array('piece_id' => '575', 'piece_nom' => 'AIRBAG TABLEAU DE BORD', 'cat_id' => '21'),
            array('piece_id' => '576', 'piece_nom' => 'AIRBAG TOIT AVD', 'cat_id' => '21'),
            array('piece_id' => '577', 'piece_nom' => 'AIRBAG TOIT AVG', 'cat_id' => '21'),
            array('piece_id' => '578', 'piece_nom' => 'AIRBAG VOLANT', 'cat_id' => '21'),
            array('piece_id' => '579', 'piece_nom' => 'CONTACTEUR ANNULAIRE AIRBAG', 'cat_id' => '21'),
            array('piece_id' => '580', 'piece_nom' => 'ANCRAGE CEINTURE ARC', 'cat_id' => '21'),
            array('piece_id' => '581', 'piece_nom' => 'ANCRAGE CEINTURE ARD', 'cat_id' => '21'),
            array('piece_id' => '582', 'piece_nom' => 'ANCRAGE CEINTURE ARG', 'cat_id' => '21'),
            array('piece_id' => '583', 'piece_nom' => 'ANCRAGE CEINTURE AVC', 'cat_id' => '21'),
            array('piece_id' => '584', 'piece_nom' => 'ANCRAGE CEINTURE AVD', 'cat_id' => '21'),
            array('piece_id' => '585', 'piece_nom' => 'ANCRAGE CEINTURE AVG', 'cat_id' => '21'),
            array('piece_id' => '586', 'piece_nom' => 'ANCRAGE CEINTURE CENTRALE AR', 'cat_id' => '21'),
            array('piece_id' => '587', 'piece_nom' => 'ANCRAGE CEINTURE CENTRALE AV', 'cat_id' => '21'),
            array('piece_id' => '588', 'piece_nom' => 'BOITIER PRETENTIONNEUR', 'cat_id' => '21'),
            array('piece_id' => '589', 'piece_nom' => 'BOITIER PYROTECHNIQUE', 'cat_id' => '21'),
            array('piece_id' => '590', 'piece_nom' => 'CEINTURE ARC', 'cat_id' => '21'),
            array('piece_id' => '591', 'piece_nom' => 'CEINTURE ARD', 'cat_id' => '21'),
            array('piece_id' => '592', 'piece_nom' => 'CEINTURE ARG', 'cat_id' => '21'),
            array('piece_id' => '593', 'piece_nom' => 'CEINTURE AVC', 'cat_id' => '21'),
            array('piece_id' => '594', 'piece_nom' => 'CEINTURE AVD', 'cat_id' => '21'),
            array('piece_id' => '595', 'piece_nom' => 'CEINTURE AVG', 'cat_id' => '21'),
            array('piece_id' => '596', 'piece_nom' => 'CEINTURE CENTRALE ARRIERE', 'cat_id' => '21'),
            array('piece_id' => '597', 'piece_nom' => 'CEINTURE CENTRALE AVANT', 'cat_id' => '21'),
            array('piece_id' => '598', 'piece_nom' => 'PRETENTIONNEUR AVD', 'cat_id' => '21'),
            array('piece_id' => '599', 'piece_nom' => 'PRETENTIONNEUR AVG', 'cat_id' => '21'),
            array('piece_id' => '600', 'piece_nom' => 'BLOC COMMODOS', 'cat_id' => '22'),
            array('piece_id' => '601', 'piece_nom' => 'BOUTON DE WARNING', 'cat_id' => '22'),
            array('piece_id' => '602', 'piece_nom' => 'COMMANDE AUTORADIO', 'cat_id' => '22'),
            array('piece_id' => '603', 'piece_nom' => 'COMMANDE CLIGNOTANT', 'cat_id' => '22'),
            array('piece_id' => '604', 'piece_nom' => 'COMMANDE DE CHAUFFAGE', 'cat_id' => '22'),
            array('piece_id' => '605', 'piece_nom' => 'COMMANDE ECLAIRAGE', 'cat_id' => '22'),
            array('piece_id' => '606', 'piece_nom' => 'COMMANDE ESSUIE GLACE', 'cat_id' => '22'),
            array('piece_id' => '607', 'piece_nom' => 'COMMANDE REGULATEUR DE VITESSE', 'cat_id' => '22'),
            array('piece_id' => '608', 'piece_nom' => 'INTER.CDE FREIN A MAIN', 'cat_id' => '22'),
            array('piece_id' => '609', 'piece_nom' => 'INTER.CDE PHARES', 'cat_id' => '22'),
            array('piece_id' => '610', 'piece_nom' => 'BOITE A GANTS', 'cat_id' => '22'),
            array('piece_id' => '611', 'piece_nom' => 'CASQUETTE SUP TABLEAU DE BORD', 'cat_id' => '22'),
            array('piece_id' => '612', 'piece_nom' => 'CONSOLE', 'cat_id' => '22'),
            array('piece_id' => '613', 'piece_nom' => 'ENTOURAGE COMPTEUR', 'cat_id' => '22'),
            array('piece_id' => '614', 'piece_nom' => 'PLANCHE DE BORD', 'cat_id' => '22'),
            array('piece_id' => '615', 'piece_nom' => 'PORTE BOITE A GANTS', 'cat_id' => '22'),
            array('piece_id' => '616', 'piece_nom' => 'AFFICHEUR DIGITAL', 'cat_id' => '22'),
            array('piece_id' => '617', 'piece_nom' => 'BLOC COMPTEUR + BSI', 'cat_id' => '22'),
            array('piece_id' => '618', 'piece_nom' => 'BLOC COMPTEURS', 'cat_id' => '22'),
            array('piece_id' => '619', 'piece_nom' => 'CABLE COMPTEUR', 'cat_id' => '22'),
            array('piece_id' => '620', 'piece_nom' => 'COMPTE TOURS', 'cat_id' => '22'),
            array('piece_id' => '621', 'piece_nom' => 'COMPTEUR', 'cat_id' => '22'),
            array('piece_id' => '622', 'piece_nom' => 'BLOC DE CHAUFFAGE COMPLET', 'cat_id' => '23'),
            array('piece_id' => '623', 'piece_nom' => 'MOTEUR CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '624', 'piece_nom' => 'MOTEUR VENTILATEUR CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '625', 'piece_nom' => 'MOTEUR VOLET DE CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '626', 'piece_nom' => 'RADIATEUR DE CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '627', 'piece_nom' => 'RESISTANCE DE CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '628', 'piece_nom' => 'VENTILATEUR DE CHAUFFAGE', 'cat_id' => '23'),
            array('piece_id' => '629', 'piece_nom' => 'WEBASTO', 'cat_id' => '23'),
            array('piece_id' => '630', 'piece_nom' => 'COMPRESSEUR AIR CONDITIONNE', 'cat_id' => '23'),
            array('piece_id' => '631', 'piece_nom' => 'CONDENSEUR CLIM', 'cat_id' => '23'),
            array('piece_id' => '632', 'piece_nom' => 'FILTRE HABITACLE', 'cat_id' => '23'),
            array('piece_id' => '633', 'piece_nom' => 'MOTEUR VENTILATEUR CLIM', 'cat_id' => '23'),
            array('piece_id' => '634', 'piece_nom' => 'SUPPORT DE COMPRESSEUR', 'cat_id' => '23'),
            array('piece_id' => '635', 'piece_nom' => 'TUYAU DE CLIM', 'cat_id' => '23'),
            array('piece_id' => '636', 'piece_nom' => 'BUSE VENTILATEUR', 'cat_id' => '23'),
            array('piece_id' => '637', 'piece_nom' => 'DURIT INFERIEURE RADIATEUR', 'cat_id' => '23'),
            array('piece_id' => '638', 'piece_nom' => 'DURIT SUPERIEURE RADIATEUR', 'cat_id' => '23'),
            array('piece_id' => '639', 'piece_nom' => 'MOTEUR VENTILATEUR RADIATEUR', 'cat_id' => '23'),
            array('piece_id' => '640', 'piece_nom' => 'POMPE A EAU', 'cat_id' => '23'),
            array('piece_id' => '641', 'piece_nom' => 'RADIATEUR', 'cat_id' => '23'),
            array('piece_id' => '642', 'piece_nom' => 'RADIATEUR / CONDENSEUR CLIM', 'cat_id' => '23'),
            array('piece_id' => '643', 'piece_nom' => 'RADIATEUR HUILE', 'cat_id' => '23'),
            array('piece_id' => '644', 'piece_nom' => 'Radiateur Refroidissement + Clim', 'cat_id' => '23'),
            array('piece_id' => '645', 'piece_nom' => 'SUPPORT DE VENTILATEUR', 'cat_id' => '23'),
            array('piece_id' => '646', 'piece_nom' => 'SUPPORT RADIATEUR', 'cat_id' => '23'),
            array('piece_id' => '647', 'piece_nom' => 'VASE EXPANSION', 'cat_id' => '23'),
            array('piece_id' => '648', 'piece_nom' => 'VENTILATEUR DE REFROIDISSEMENT', 'cat_id' => '23'),
            array('piece_id' => '649', 'piece_nom' => 'AMORTISSEUR ARD', 'cat_id' => '24'),
            array('piece_id' => '650', 'piece_nom' => 'AMORTISSEUR ARG', 'cat_id' => '24'),
            array('piece_id' => '651', 'piece_nom' => 'COUPELLES AMORTISSEURS AR', 'cat_id' => '24'),
            array('piece_id' => '652', 'piece_nom' => 'LAME DE RESSORT ARD', 'cat_id' => '24'),
            array('piece_id' => '653', 'piece_nom' => 'LAME DE RESSORT ARG', 'cat_id' => '24'),
            array('piece_id' => '654', 'piece_nom' => 'RESSORT AMORTISSEUR ARD', 'cat_id' => '24'),
            array('piece_id' => '655', 'piece_nom' => 'RESSORT AMORTISSEUR ARG', 'cat_id' => '24'),
            array('piece_id' => '656', 'piece_nom' => 'SPHERE CENTRAL DE RAIDEUR AR', 'cat_id' => '24'),
            array('piece_id' => '657', 'piece_nom' => 'SPHERES SUSPENSION ARD', 'cat_id' => '24'),
            array('piece_id' => '658', 'piece_nom' => 'SPHERES SUSPENSION ARG', 'cat_id' => '24'),
            array('piece_id' => '659', 'piece_nom' => 'VERIN SUSPENSION    ARD', 'cat_id' => '24'),
            array('piece_id' => '660', 'piece_nom' => 'VERIN SUSPENSION    ARG', 'cat_id' => '24'),
            array('piece_id' => '661', 'piece_nom' => 'VERIN SUSPENSION AR', 'cat_id' => '24'),
            array('piece_id' => '662', 'piece_nom' => 'BARRE STAB AR', 'cat_id' => '24'),
            array('piece_id' => '663', 'piece_nom' => 'BIELLETTE BARRE STAB ARD', 'cat_id' => '24'),
            array('piece_id' => '664', 'piece_nom' => 'BIELLETTE BARRE STAB ARG', 'cat_id' => '24'),
            array('piece_id' => '665', 'piece_nom' => 'BRAS ARD', 'cat_id' => '24'),
            array('piece_id' => '666', 'piece_nom' => 'BRAS ARG', 'cat_id' => '24'),
            array('piece_id' => '667', 'piece_nom' => 'DEMI TRAIN ARD', 'cat_id' => '24'),
            array('piece_id' => '668', 'piece_nom' => 'DEMI TRAIN ARG', 'cat_id' => '24'),
            array('piece_id' => '669', 'piece_nom' => 'FUSEE ARD', 'cat_id' => '24'),
            array('piece_id' => '670', 'piece_nom' => 'FUSEE ARG', 'cat_id' => '24'),
            array('piece_id' => '671', 'piece_nom' => 'MOYEU ARD', 'cat_id' => '24'),
            array('piece_id' => '672', 'piece_nom' => 'MOYEU ARG', 'cat_id' => '24'),
            array('piece_id' => '673', 'piece_nom' => 'PIVOT ARD', 'cat_id' => '24'),
            array('piece_id' => '674', 'piece_nom' => 'PIVOT ARG', 'cat_id' => '24'),
            array('piece_id' => '675', 'piece_nom' => 'TIRANT DE CHASSE ARD', 'cat_id' => '24'),
            array('piece_id' => '676', 'piece_nom' => 'TIRANT DE CHASSE ARG', 'cat_id' => '24'),
            array('piece_id' => '677', 'piece_nom' => 'TRIANGLE INF ARD', 'cat_id' => '24'),
            array('piece_id' => '678', 'piece_nom' => 'TRIANGLE INF ARG', 'cat_id' => '24'),
            array('piece_id' => '679', 'piece_nom' => 'TRIANGLE SUP ARD', 'cat_id' => '24'),
            array('piece_id' => '680', 'piece_nom' => 'TRIANGLE SUP ARG', 'cat_id' => '24'),
            array('piece_id' => '681', 'piece_nom' => 'BERCEAU AR', 'cat_id' => '24'),
            array('piece_id' => '682', 'piece_nom' => 'TRAIN AR', 'cat_id' => '24'),
            array('piece_id' => '683', 'piece_nom' => 'AMORTISSEUR AVD', 'cat_id' => '25'),
            array('piece_id' => '684', 'piece_nom' => 'AMORTISSEUR AVG', 'cat_id' => '25'),
            array('piece_id' => '685', 'piece_nom' => 'NECESSAIRE ANCRAGE AMORTISSEURS AV', 'cat_id' => '25'),
            array('piece_id' => '686', 'piece_nom' => 'RESSORT AMORTISSEUR AVD', 'cat_id' => '25'),
            array('piece_id' => '687', 'piece_nom' => 'RESSORT AMORTISSEUR AVG', 'cat_id' => '25'),
            array('piece_id' => '688', 'piece_nom' => 'SPHERE ANTI-AFFAISSEMENT', 'cat_id' => '25'),
            array('piece_id' => '689', 'piece_nom' => 'SPHERE CENTRAL DE RAIDEUR AV', 'cat_id' => '25'),
            array('piece_id' => '690', 'piece_nom' => 'SPHERES ACCUMULATEURS', 'cat_id' => '25'),
            array('piece_id' => '691', 'piece_nom' => 'VERIN SUSPENSION AV', 'cat_id' => '25'),
            array('piece_id' => '692', 'piece_nom' => 'VERIN SUSPENSION AVD', 'cat_id' => '25'),
            array('piece_id' => '693', 'piece_nom' => 'VERIN SUSPENSION AVG', 'cat_id' => '25'),
            array('piece_id' => '694', 'piece_nom' => 'BARRE STAB AV', 'cat_id' => '25'),
            array('piece_id' => '695', 'piece_nom' => 'BIELLETTE BARRE STAB AVD', 'cat_id' => '25'),
            array('piece_id' => '696', 'piece_nom' => 'BRAS AVD', 'cat_id' => '25'),
            array('piece_id' => '697', 'piece_nom' => 'BRAS AVG', 'cat_id' => '25'),
            array('piece_id' => '698', 'piece_nom' => 'DEMI TRAIN AVD', 'cat_id' => '25'),
            array('piece_id' => '699', 'piece_nom' => 'DEMI TRAIN AVG', 'cat_id' => '25'),
            array('piece_id' => '700', 'piece_nom' => 'FUSEE AVD', 'cat_id' => '25'),
            array('piece_id' => '701', 'piece_nom' => 'FUSEE AVG', 'cat_id' => '25'),
            array('piece_id' => '702', 'piece_nom' => 'MOYEU AVD', 'cat_id' => '25'),
            array('piece_id' => '703', 'piece_nom' => 'MOYEU AVG', 'cat_id' => '25'),
            array('piece_id' => '704', 'piece_nom' => 'PIVOT AVD', 'cat_id' => '25'),
            array('piece_id' => '705', 'piece_nom' => 'PIVOT AVG', 'cat_id' => '25'),
            array('piece_id' => '706', 'piece_nom' => 'TIRANT DE CHASSE AVD', 'cat_id' => '25'),
            array('piece_id' => '707', 'piece_nom' => 'TIRANT DE CHASSE AVG', 'cat_id' => '25'),
            array('piece_id' => '708', 'piece_nom' => 'TRIANGLE INF AVD', 'cat_id' => '25'),
            array('piece_id' => '709', 'piece_nom' => 'TRIANGLE INF AVG', 'cat_id' => '25'),
            array('piece_id' => '710', 'piece_nom' => 'TRIANGLE SUP AVD', 'cat_id' => '25'),
            array('piece_id' => '711', 'piece_nom' => 'TRIANGLE SUP AVG', 'cat_id' => '25'),
            array('piece_id' => '712', 'piece_nom' => 'BERCEAU MOTEUR AV', 'cat_id' => '25'),
            array('piece_id' => '713', 'piece_nom' => 'SUPPORT TRIANGLE INFERIEUR AVD', 'cat_id' => '25'),
            array('piece_id' => '714', 'piece_nom' => 'SUPPORT TRIANGLE INFERIEUR AVG', 'cat_id' => '25'),
            array('piece_id' => '715', 'piece_nom' => 'TRAIN AV', 'cat_id' => '25'),
            array('piece_id' => '716', 'piece_nom' => 'PARE-BRISE', 'cat_id' => '26'),
            array('piece_id' => '717', 'piece_nom' => 'GLACE AR TOIT OUVRANT', 'cat_id' => '26'),
            array('piece_id' => '718', 'piece_nom' => 'GLACE TOIT OUVRANT', 'cat_id' => '26'),
            array('piece_id' => '719', 'piece_nom' => 'GLACE AR CABINE', 'cat_id' => '26'),
            array('piece_id' => '720', 'piece_nom' => 'GLACE D PANNEAU AR', 'cat_id' => '26'),
            array('piece_id' => '721', 'piece_nom' => 'GLACE G PANNEAU AR', 'cat_id' => '26'),
            array('piece_id' => '722', 'piece_nom' => 'GLACE PORTE BATTANTE', 'cat_id' => '26'),
            array('piece_id' => '723', 'piece_nom' => 'GLACE PORTE BATTANTE D', 'cat_id' => '26'),
            array('piece_id' => '724', 'piece_nom' => 'GLACE PORTE BATTANTE G', 'cat_id' => '26'),
            array('piece_id' => '725', 'piece_nom' => 'GLACE AILE AR D', 'cat_id' => '26'),
            array('piece_id' => '726', 'piece_nom' => 'GLACE AILE AR G', 'cat_id' => '26'),
            array('piece_id' => '727', 'piece_nom' => 'GLACE AILE AV', 'cat_id' => '26'),
            array('piece_id' => '728', 'piece_nom' => 'GLACE AILE AV D', 'cat_id' => '26'),
            array('piece_id' => '729', 'piece_nom' => 'GLACE AILE AV G', 'cat_id' => '26'),
            array('piece_id' => '730', 'piece_nom' => 'GLACE HAYON', 'cat_id' => '26'),
            array('piece_id' => '731', 'piece_nom' => 'GLACE LUNETTE AR', 'cat_id' => '26'),
            array('piece_id' => '732', 'piece_nom' => 'GLACE SEPARATION HABITACLE', 'cat_id' => '26'),
            array('piece_id' => '733', 'piece_nom' => 'GLACE SUP HAYON', 'cat_id' => '26'),
            array('piece_id' => '734', 'piece_nom' => 'GLACE AR CUSTODE D', 'cat_id' => '26'),
            array('piece_id' => '735', 'piece_nom' => 'GLACE AR CUSTODE G', 'cat_id' => '26'),
            array('piece_id' => '736', 'piece_nom' => 'GLACE AV CUSTODE D', 'cat_id' => '26'),
            array('piece_id' => '737', 'piece_nom' => 'GLACE AV CUSTODE G', 'cat_id' => '26'),
            array('piece_id' => '738', 'piece_nom' => 'GLACE CUSTODE D', 'cat_id' => '26'),
            array('piece_id' => '739', 'piece_nom' => 'GLACE CUSTODE G', 'cat_id' => '26'),
            array('piece_id' => '740', 'piece_nom' => 'GLACE MOBILE CUSTODE D', 'cat_id' => '26'),
            array('piece_id' => '741', 'piece_nom' => 'GLACE MOBILE CUSTODE G', 'cat_id' => '26'),
            array('piece_id' => '742', 'piece_nom' => 'GLACE AR COULISSANTE PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '743', 'piece_nom' => 'GLACE AR COULISSANTE PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '744', 'piece_nom' => 'GLACE AR PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '745', 'piece_nom' => 'GLACE AR PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '746', 'piece_nom' => 'GLACE AV COULISSANTE PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '747', 'piece_nom' => 'GLACE AV COULISSANTE PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '748', 'piece_nom' => 'GLACE AV PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '749', 'piece_nom' => 'GLACE AV PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '750', 'piece_nom' => 'GLACE AVEC CADRE PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '751', 'piece_nom' => 'GLACE AVEC CADRE PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '752', 'piece_nom' => 'GLACE COULISSANTE PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '753', 'piece_nom' => 'GLACE COULISSANTE PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '754', 'piece_nom' => 'GLACE PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '755', 'piece_nom' => 'GLACE PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '756', 'piece_nom' => 'GLACE SUP PANNEAU LAT D', 'cat_id' => '26'),
            array('piece_id' => '757', 'piece_nom' => 'GLACE SUP PANNEAU LAT G', 'cat_id' => '26'),
            array('piece_id' => '758', 'piece_nom' => 'GLACE AR D PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '759', 'piece_nom' => 'GLACE AR G PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '760', 'piece_nom' => 'GLACE AR PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '761', 'piece_nom' => 'GLACE AV D PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '762', 'piece_nom' => 'GLACE AV G PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '763', 'piece_nom' => 'GLACE AV PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '764', 'piece_nom' => 'GLACE DE PAVILLON', 'cat_id' => '26'),
            array('piece_id' => '765', 'piece_nom' => 'GLACE COULISSANTE AV PORTE AR D', 'cat_id' => '26'),
            array('piece_id' => '766', 'piece_nom' => 'GLACE COULISSANTE AV PORTE AR G', 'cat_id' => '26'),
            array('piece_id' => '767', 'piece_nom' => 'GLACE DEFLECTEUR PORTE AR D', 'cat_id' => '26'),
            array('piece_id' => '768', 'piece_nom' => 'GLACE DEFLECTEUR PORTE AR G', 'cat_id' => '26'),
            array('piece_id' => '769', 'piece_nom' => 'GLACE FIXE PORTE AR D', 'cat_id' => '26'),
            array('piece_id' => '770', 'piece_nom' => 'GLACE FIXE PORTE AR G', 'cat_id' => '26'),
            array('piece_id' => '771', 'piece_nom' => 'GLACE PORTE AR D', 'cat_id' => '26'),
            array('piece_id' => '772', 'piece_nom' => 'GLACE PORTE AR G', 'cat_id' => '26'),
            array('piece_id' => '773', 'piece_nom' => 'GLACE DEFLECTEUR PORTE AV D', 'cat_id' => '26'),
            array('piece_id' => '774', 'piece_nom' => 'GLACE DEFLECTEUR PORTE AV G', 'cat_id' => '26'),
            array('piece_id' => '775', 'piece_nom' => 'GLACE FIXE PORTE AV D', 'cat_id' => '26'),
            array('piece_id' => '776', 'piece_nom' => 'GLACE FIXE PORTE AV G', 'cat_id' => '26'),
            array('piece_id' => '777', 'piece_nom' => 'GLACE PORTE AV D', 'cat_id' => '26'),
            array('piece_id' => '778', 'piece_nom' => 'GLACE PORTE AV G', 'cat_id' => '26'),
            array('piece_id' => '779', 'piece_nom' => 'GLACE COULISSANTE PORTE COULISSANTE D', 'cat_id' => '26'),
            array('piece_id' => '780', 'piece_nom' => 'GLACE COULISSANTE PORTE COULISSANTE G', 'cat_id' => '26'),
            array('piece_id' => '781', 'piece_nom' => 'GLACE FIXE PORTE COULISSANTE D', 'cat_id' => '26'),
            array('piece_id' => '782', 'piece_nom' => 'GLACE FIXE PORTE COULISSANTE G', 'cat_id' => '26'),
            array('piece_id' => '783', 'piece_nom' => 'GLACE PORTE COULISSANTE D', 'cat_id' => '26'),
            array('piece_id' => '784', 'piece_nom' => 'GLACE PORTE COULISSANTE G', 'cat_id' => '26')
        );

        DB::table('piece')->insert($piece);
    }
}
