<?php

use Illuminate\Database\Seeder;

class PieceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $piece = array(
            array('piece_id' => '1', 'piece_nom' => 'ECLAIRAGE GAUCHE', 'piece_symbole' => 'ECLAIRAGE GAUCHE.jpg', 'cat_id' => '1'),
            array('piece_id' => '2', 'piece_nom' => 'ECLAIRAGE DROIT', 'piece_symbole' => 'ECLAIRAGE DROIT.jpg', 'cat_id' => '1'),
            array('piece_id' => '3', 'piece_nom' => 'CAPOT', 'piece_symbole' => 'CAPOT.jpg', 'cat_id' => '1'),
            array('piece_id' => '4', 'piece_nom' => 'AILE DROITE', 'piece_symbole' => 'AILE DROITE.jpg', 'cat_id' => '1'),
            array('piece_id' => '5', 'piece_nom' => 'AILE GAUCHE', 'piece_symbole' => 'AILE GAUCHE.jpg', 'cat_id' => '1'),
            array('piece_id' => '6', 'piece_nom' => 'VITRAGE', 'piece_symbole' => 'VITRAGE.jpg', 'cat_id' => '1'),
            array('piece_id' => '7', 'piece_nom' => 'CALANDRE', 'piece_symbole' => 'CALANDRE.jpg', 'cat_id' => '1'),
            array('piece_id' => '8', 'piece_nom' => 'RETROVISEUR DROIT', 'piece_symbole' => 'RETROVISEUR DROIT.jpg', 'cat_id' => '1'),
            array('piece_id' => '9', 'piece_nom' => 'RETROVISEUR GAUCHE', 'piece_symbole' => 'RETROVISEUR GAUCHE.jpg', 'cat_id' => '1'),
            array('piece_id' => '10', 'piece_nom' => 'PARE-CHOC ARRIERE', 'piece_symbole' => 'PARE-CHOC ARRIERE.jpg', 'cat_id' => '2'),
            array('piece_id' => '11', 'piece_nom' => 'HAYON', 'piece_symbole' => 'HAYON.jpg', 'cat_id' => '2'),
            array('piece_id' => '12', 'piece_nom' => 'FEUX ARRIERE DROIT', 'piece_symbole' => 'FEUX ARRIERE DROIT.jpg', 'cat_id' => '2'),
            array('piece_id' => '13', 'piece_nom' => 'FEUX ARRIERE GAUCHE', 'piece_symbole' => 'FEUX ARRIERE GAUCHE.jpg', 'cat_id' => '2'),
            array('piece_id' => '14', 'piece_nom' => 'Colonne de direction assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '15', 'piece_nom' => 'Colonne de direction non assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '16', 'piece_nom' => 'Cremaillere', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '17', 'piece_nom' => 'Cremaillere hydraulique', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '18', 'piece_nom' => 'Cremaillere non assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '19', 'piece_nom' => 'Pompe direction assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '20', 'piece_nom' => 'Moteur electrique de direction assistée', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '21', 'piece_nom' => 'Boitier de direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '22', 'piece_nom' => 'Calculateur direction assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '23', 'piece_nom' => 'Poulie pompe direc assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '24', 'piece_nom' => 'Relais de direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '25', 'piece_nom' => 'Verin direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '26', 'piece_nom' => 'Volant de direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '27', 'piece_nom' => 'Cardan de direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '28', 'piece_nom' => 'Coquille de volant', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '29', 'piece_nom' => 'Flexible direction assistee', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '30', 'piece_nom' => 'Reservoir pompe direction', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '31', 'piece_nom' => 'Rotule de direction droite', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '32', 'piece_nom' => 'Rotule de direction gauche', 'piece_symbole' => '', 'cat_id' => '3'),
            array('piece_id' => '33', 'piece_nom' => 'Collecteur admission', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '34', 'piece_nom' => 'Collecteur echappement', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '35', 'piece_nom' => 'Catalyseur', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '36', 'piece_nom' => 'Flexible echappement av', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '37', 'piece_nom' => 'Precatalyseur', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '38', 'piece_nom' => 'Silencieux arrière', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '39', 'piece_nom' => 'Silencieux avant', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '40', 'piece_nom' => 'Silencieux intermediaire', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '41', 'piece_nom' => 'Sonde lambda', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '42', 'piece_nom' => 'Tube echappement', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '43', 'piece_nom' => 'Support echap', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '44', 'piece_nom' => 'Collier echappement', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '45', 'piece_nom' => 'Manchon', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '46', 'piece_nom' => 'Silentbloc echappement', 'piece_symbole' => '', 'cat_id' => '4'),
            array('piece_id' => '47', 'piece_nom' => 'Enjoliveur de roue', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '48', 'piece_nom' => 'Jante tole', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '49', 'piece_nom' => 'Jante aluminium', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '50', 'piece_nom' => 'Bac roue de secours', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '51', 'piece_nom' => 'Cric', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '52', 'piece_nom' => 'Cric + manivelle', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '53', 'piece_nom' => 'Manivelle de cric', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '54', 'piece_nom' => 'Panier roue secours', 'piece_symbole' => '', 'cat_id' => '5'),
            array('piece_id' => '55', 'piece_nom' => 'Etrier de frein avant droit', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '56', 'piece_nom' => 'Etrier de frein avant gauche', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '57', 'piece_nom' => 'Capteur abs ard', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '58', 'piece_nom' => 'Capteur abs avd', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '59', 'piece_nom' => 'Unité hydraulique ABS', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '60', 'piece_nom' => 'Capteur abs arg', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '61', 'piece_nom' => 'Capteur abs avg', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '62', 'piece_nom' => 'Bloc regulateur', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '63', 'piece_nom' => 'Calculateur abs', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '64', 'piece_nom' => 'Levier frein a main', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '65', 'piece_nom' => 'Pedale de frein', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '66', 'piece_nom' => 'Pedalier complet', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '67', 'piece_nom' => 'Maitre cylindre', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '68', 'piece_nom' => 'Pompe a vide', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '69', 'piece_nom' => 'Servo-frein', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '70', 'piece_nom' => 'Bocal liquide frein', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '71', 'piece_nom' => 'Limiteur/repartiteur de pression arriere', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '72', 'piece_nom' => 'Boitier suspension hydractive', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '73', 'piece_nom' => 'Conjoncteur', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '74', 'piece_nom' => 'Correcteur de hauteur ar', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '75', 'piece_nom' => 'Correcteur de hauteur av', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '76', 'piece_nom' => 'Pompe hydraulique lhm', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '77', 'piece_nom' => 'Regulateur de raideur ar', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '78', 'piece_nom' => 'Reservoir lhm', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '79', 'piece_nom' => 'Disque arriere', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '80', 'piece_nom' => 'Disque avant', 'piece_symbole' => '', 'cat_id' => '6'),
            array('piece_id' => '81', 'piece_nom' => 'Train arrière', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '82', 'piece_nom' => 'Etrier de frein arrière droit', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '83', 'piece_nom' => 'Etrier de frein arrière gauche', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '84', 'piece_nom' => 'Tambour arrière droit', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '85', 'piece_nom' => 'Tambour arrière gauche', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '86', 'piece_nom' => 'Flasque ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '87', 'piece_nom' => 'Flasque arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '88', 'piece_nom' => 'Barre stab ar', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '89', 'piece_nom' => 'Biellette barre stab ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '90', 'piece_nom' => 'Biellette barre stab arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '91', 'piece_nom' => 'Triangle inf ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '92', 'piece_nom' => 'Triangle sup ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '93', 'piece_nom' => 'Triangle inf arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '94', 'piece_nom' => 'Demi train arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '95', 'piece_nom' => 'Fusee ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '96', 'piece_nom' => 'Moyeu ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '97', 'piece_nom' => 'Pivot ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '98', 'piece_nom' => 'Tirant de chasse ard', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '99', 'piece_nom' => 'Fusee arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '100', 'piece_nom' => 'Moyeu arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '101', 'piece_nom' => 'Pivot arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '102', 'piece_nom' => 'Tirant de chasse arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '103', 'piece_nom' => 'Triangle sup arg', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '104', 'piece_nom' => 'Berceau ar', 'piece_symbole' => '', 'cat_id' => '7'),
            array('piece_id' => '105', 'piece_nom' => 'Amortisseur arrière droit', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '106', 'piece_nom' => 'Amortisseur arrière gauche', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '107', 'piece_nom' => 'Ressort amortisseur ard', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '108', 'piece_nom' => 'Spheres suspension ard', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '109', 'piece_nom' => 'Spheres suspension arg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '110', 'piece_nom' => 'Coupelles amortisseurs ar', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '111', 'piece_nom' => 'Lame de ressort ard', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '112', 'piece_nom' => 'Lame de ressort arg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '113', 'piece_nom' => 'Sphere central de raideur ar', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '114', 'piece_nom' => 'Verin suspension ar', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '115', 'piece_nom' => 'Verin suspension ard', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '116', 'piece_nom' => 'Verin suspension arg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '117', 'piece_nom' => 'Ressort amortisseur arg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '118', 'piece_nom' => 'Amortisseur avant droit', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '119', 'piece_nom' => 'Amortisseur avant gauche', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '120', 'piece_nom' => 'Ressort amortisseur avd', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '121', 'piece_nom' => 'Sphere anti-affaissement', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '122', 'piece_nom' => 'Sphere central de raideur av', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '123', 'piece_nom' => 'Spheres accumulateurs', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '124', 'piece_nom' => 'Necessaire ancrage amortisseurs av', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '125', 'piece_nom' => 'Verin suspension av', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '126', 'piece_nom' => 'Verin suspension avd', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '127', 'piece_nom' => 'Verin suspension avg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '128', 'piece_nom' => 'Ressort amortisseur avg', 'piece_symbole' => '', 'cat_id' => '8'),
            array('piece_id' => '129', 'piece_nom' => 'Demi train arrière droit', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '130', 'piece_nom' => 'Bras ard', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '131', 'piece_nom' => 'Bras arg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '132', 'piece_nom' => 'Barre stab av', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '133', 'piece_nom' => 'Biellette barre stab avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '134', 'piece_nom' => 'Demi train avant gauche', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '135', 'piece_nom' => 'Biellette barre stab avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '136', 'piece_nom' => 'Bras avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '137', 'piece_nom' => 'Moyeu avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '138', 'piece_nom' => 'Triangle inf avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '139', 'piece_nom' => 'Triangle sup avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '140', 'piece_nom' => 'Bras avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '141', 'piece_nom' => 'Triangle inf avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '142', 'piece_nom' => 'Triangle sup avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '143', 'piece_nom' => 'Demi train avant droit', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '144', 'piece_nom' => 'Fusee avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '145', 'piece_nom' => 'Pivot avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '146', 'piece_nom' => 'Tirant de chasse avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '147', 'piece_nom' => 'Fusee avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '148', 'piece_nom' => 'Moyeu avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '149', 'piece_nom' => 'Pivot avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '150', 'piece_nom' => 'Tirant de chasse avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '151', 'piece_nom' => 'Support triangle inferieur avd', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '152', 'piece_nom' => 'Support triangle inferieur avg', 'piece_symbole' => '', 'cat_id' => '9'),
            array('piece_id' => '153', 'piece_nom' => 'Berceau moteur avant', 'piece_symbole' => '', 'cat_id' => '10'),
            array('piece_id' => '154', 'piece_nom' => 'Train avant', 'piece_symbole' => '', 'cat_id' => '10'),
            array('piece_id' => '155', 'piece_nom' => 'Moteur diesel', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '156', 'piece_nom' => 'Moteur essence', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '157', 'piece_nom' => 'Vilebrequin', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '158', 'piece_nom' => 'Poulie de vilebrequin', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '159', 'piece_nom' => 'Volant moteur', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '160', 'piece_nom' => 'Bloc moteur nu', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '161', 'piece_nom' => 'Bloc embielle', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '162', 'piece_nom' => 'Culasse essence', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '163', 'piece_nom' => 'Arbre a cames', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '164', 'piece_nom' => 'Couvre culasse', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '165', 'piece_nom' => 'Culasse diesel', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '166', 'piece_nom' => 'Poulie arbre a cames', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '167', 'piece_nom' => 'Refroidisseur filtre a huile', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '168', 'piece_nom' => 'Carter inf moteur', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '169', 'piece_nom' => 'Jauge a huile', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '170', 'piece_nom' => 'Pompe a huile', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '171', 'piece_nom' => 'Protection carter huile', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '172', 'piece_nom' => 'Puits de jauge', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '173', 'piece_nom' => 'Support filtre a huile', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '174', 'piece_nom' => 'Support moteur', 'piece_symbole' => '', 'cat_id' => '11'),
            array('piece_id' => '175', 'piece_nom' => 'Boîte à vitesse mecanique', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '176', 'piece_nom' => 'Boîte à vitesse automatique', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '177', 'piece_nom' => 'Support boite de vitesse', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '178', 'piece_nom' => 'Transmission avant droite', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '179', 'piece_nom' => 'Transmission avant gauche', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '180', 'piece_nom' => 'Transmission arrière droite', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '181', 'piece_nom' => 'Transmission arrière gauche', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '182', 'piece_nom' => 'Transmission longitudinale av', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '183', 'piece_nom' => 'Transmission longitudinale', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '184', 'piece_nom' => 'Transmission longitudinale ar', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '185', 'piece_nom' => 'Transmission longitudinale cent', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '186', 'piece_nom' => 'Pont avant', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '187', 'piece_nom' => 'Pont arriere', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '188', 'piece_nom' => 'Levier de vitesses', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '189', 'piece_nom' => 'Boite de transfert', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '190', 'piece_nom' => 'Boitier de commande bv auto', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '191', 'piece_nom' => 'Calculateur boite auto', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '192', 'piece_nom' => 'Contacteur feux recul', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '193', 'piece_nom' => 'Echangeur refroid huile boite', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '194', 'piece_nom' => 'Pommeau levier vitesses', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '195', 'piece_nom' => 'Selecteur de vitesse', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '196', 'piece_nom' => 'Tringlerie boite', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '197', 'piece_nom' => 'Flector', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '198', 'piece_nom' => 'Butee embrayage hydraulique', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '199', 'piece_nom' => 'Cable embrayage', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '200', 'piece_nom' => 'Convertisseur', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '201', 'piece_nom' => 'Emetteur embrayage', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '202', 'piece_nom' => 'Kit embrayage', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '203', 'piece_nom' => 'Pedale embrayage', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '204', 'piece_nom' => 'Recepteur embrayage', 'piece_symbole' => '', 'cat_id' => '12'),
            array('piece_id' => '205', 'piece_nom' => 'Alternateur', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '206', 'piece_nom' => 'Démarreur', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '207', 'piece_nom' => 'Support alternateur', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '208', 'piece_nom' => 'Klaxon / avertisseur', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '209', 'piece_nom' => 'Batterie', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '210', 'piece_nom' => 'Faisceau avant', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '211', 'piece_nom' => 'Faisceau electrique chauffage', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '212', 'piece_nom' => 'Faisceau moteur', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '213', 'piece_nom' => 'Faisceau tableau de bord', 'piece_symbole' => '', 'cat_id' => '13'),
            array('piece_id' => '214', 'piece_nom' => 'Boite a fusibles', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '215', 'piece_nom' => 'Platine fusible habitacle', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '216', 'piece_nom' => 'Platine fusible ar', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '217', 'piece_nom' => 'Platine fusible av', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '218', 'piece_nom' => 'Pompe à carburant immergée', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '219', 'piece_nom' => 'Volet de trappe carburant', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '220', 'piece_nom' => 'Boitier filtre a air', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '221', 'piece_nom' => 'Carburateur', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '222', 'piece_nom' => 'Pompe à carburant électrique', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '223', 'piece_nom' => 'Pompe alimentation carburant', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '224', 'piece_nom' => 'Boitier injection', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '225', 'piece_nom' => 'Electrovanne', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '226', 'piece_nom' => 'Pompe amorcage go', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '227', 'piece_nom' => 'Vanne EGR', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '228', 'piece_nom' => 'Actuateur de ralenti', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '229', 'piece_nom' => 'Bloc monopoint', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '230', 'piece_nom' => 'Boitier papillon', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '231', 'piece_nom' => 'Capteur pedale accelerateur', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '232', 'piece_nom' => 'Capteur pmh', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '233', 'piece_nom' => 'Debimetre air', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '234', 'piece_nom' => 'Distributeur injection', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '235', 'piece_nom' => 'Ensemble injecteurs', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '236', 'piece_nom' => 'Injecteur', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '237', 'piece_nom' => 'Pedale accelerateur', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '238', 'piece_nom' => 'Pompe hp', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '239', 'piece_nom' => 'Pompe injection diesel', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '240', 'piece_nom' => 'Potentiometre accelerateur', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '241', 'piece_nom' => 'Poulie crantee pompe injection', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '242', 'piece_nom' => 'Rampe injection', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '243', 'piece_nom' => 'Support de filtre carburant', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '244', 'piece_nom' => 'Tuyaux injecteurs', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '245', 'piece_nom' => 'Turbo', 'piece_symbole' => '', 'cat_id' => '14'),
            array('piece_id' => '246', 'piece_nom' => 'Allumeur', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '247', 'piece_nom' => 'Bobine allumage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '248', 'piece_nom' => 'Boitier allumage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '249', 'piece_nom' => 'Distributeur allumage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '250', 'piece_nom' => 'Module allumage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '251', 'piece_nom' => 'Tête d\'allumeur', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '252', 'piece_nom' => 'Boitier de préchauffage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '253', 'piece_nom' => 'Bougie prechauffage', 'piece_symbole' => '', 'cat_id' => '15'),
            array('piece_id' => '254', 'piece_nom' => 'Compresseur d air', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '255', 'piece_nom' => 'Echangeur air', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '256', 'piece_nom' => 'Bloc de chauffage complet', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '257', 'piece_nom' => 'Radiateur de chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '258', 'piece_nom' => 'Resistance de chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '259', 'piece_nom' => 'Moteur chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '260', 'piece_nom' => 'Moteur ventilateur chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '261', 'piece_nom' => 'Moteur volet de chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '262', 'piece_nom' => 'Ventilateur de chauffage', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '263', 'piece_nom' => 'Webasto', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '264', 'piece_nom' => 'Compresseur air conditionne', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '265', 'piece_nom' => 'Condenseur clim', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '266', 'piece_nom' => 'Filtre habitacle', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '267', 'piece_nom' => 'Support de compresseur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '268', 'piece_nom' => 'Tuyau de clim', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '269', 'piece_nom' => 'Moteur ventilateur radiateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '270', 'piece_nom' => 'Radiateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '271', 'piece_nom' => 'Radiateur / condenseur clim', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '272', 'piece_nom' => 'Support radiateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '273', 'piece_nom' => 'Vase expansion', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '274', 'piece_nom' => 'Moteur ventilateur clim', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '275', 'piece_nom' => 'Buse ventilateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '276', 'piece_nom' => 'Durit inferieure radiateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '277', 'piece_nom' => 'Durit superieure radiateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '278', 'piece_nom' => 'Pompe a eau', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '279', 'piece_nom' => 'Radiateur huile', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '280', 'piece_nom' => 'Support de ventilateur', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '281', 'piece_nom' => 'Ventilateur de refroidissement', 'piece_symbole' => '', 'cat_id' => '16'),
            array('piece_id' => '282', 'piece_nom' => 'Calculateur moteur', 'piece_symbole' => '', 'cat_id' => '17'),
            array('piece_id' => '283', 'piece_nom' => 'COMMANDE', 'piece_symbole' => 'COMMANDE.jpg', 'cat_id' => '18'),
            array('piece_id' => '284', 'piece_nom' => 'BLOC COMMODOS', 'piece_symbole' => 'BLOC COMMODOS.jpg', 'cat_id' => '18'),
            array('piece_id' => '285', 'piece_nom' => 'VOLANT', 'piece_symbole' => 'VOLANT.jpg', 'cat_id' => '18'),
            array('piece_id' => '286', 'piece_nom' => 'TABLEAU DE BORD', 'piece_symbole' => 'TABLEAU DE BORD.jpg', 'cat_id' => '18'),
            array('piece_id' => '287', 'piece_nom' => 'SELLERIE', 'piece_symbole' => 'SELLERIE.jpg', 'cat_id' => '18'),
            array('piece_id' => '288', 'piece_nom' => 'Retroviseur interieur', 'piece_symbole' => 'Retroviseur interieur.jpg', 'cat_id' => '18'),
            array('piece_id' => '289', 'piece_nom' => 'PLAGE ARRIERE', 'piece_symbole' => 'PLAGE ARRIERE.jpg', 'cat_id' => '18'),
            array('piece_id' => '290', 'piece_nom' => 'ceinture de sécurité', 'piece_symbole' => 'ceinture de sécurité.jpg', 'cat_id' => '18'),
            array('piece_id' => '291', 'piece_nom' => 'COMPTEUR', 'piece_symbole' => 'COMPTEUR.jpg', 'cat_id' => '18'),
            array('piece_id' => '292', 'piece_nom' => 'PARE-SOLEIL DROIT', 'piece_symbole' => 'PARE-SOLEIL DROIT.jpg', 'cat_id' => '18'),
            array('piece_id' => '293', 'piece_nom' => 'PARE-SOLEIL GAUCHE', 'piece_symbole' => 'PARE-SOLEIL GAUCHE.jpg', 'cat_id' => '18'),
            array('piece_id' => '294', 'piece_nom' => 'AILE ARRIERE GAUCHE', 'piece_symbole' => 'AILE ARRIERE GAUCHE.jpg', 'cat_id' => '19'),
            array('piece_id' => '295', 'piece_nom' => 'PORTE ARRIERE GAUCHE', 'piece_symbole' => 'PORTE ARRIERE GAUCHE.jpg', 'cat_id' => '19'),
            array('piece_id' => '296', 'piece_nom' => 'PORTE AVANT GAUCHE', 'piece_symbole' => 'PORTE AVANT GAUCHE.jpg', 'cat_id' => '19'),
            array('piece_id' => '297', 'piece_nom' => 'PORTE AVANT DROITE', 'piece_symbole' => 'PORTE AVANT DROITE.jpg', 'cat_id' => '19'),
            array('piece_id' => '298', 'piece_nom' => 'AILE ARRIERE DROITE', 'piece_symbole' => 'AILE ARRIERE DROITE.jpg', 'cat_id' => '19'),
            array('piece_id' => '299', 'piece_nom' => 'PORTE ARRIERE DROITE', 'piece_symbole' => 'PORTE ARRIERE DROITE.jpg', 'cat_id' => '19')
        );

        DB::table('piece')->insert($piece);
    }
}
